packages.json
=> fix: add back gnome-software-ostree

etc/dconf/db/local.d/01-ublue
This pull request is in reference to #4.
I have tested and updated the shortcut defaults to make Super + E open the home folder after a clean rebase.
=> fix: Update Super-E shortcut isn't working

etc/dconf/db/local.d/01-ublue
For some reason Fedora/GNOME doesn't enable "tap-to-click" for touchpad.    
Ubuntu has it enabled by default.    
Check it with a command:   
`gsettings get org.gnome.desktop.peripherals.touchpad tap-to-click`
=> feat: enable "tap-to-click" for touchpad

usr/share/gnome-background-properties/ublue-lagoon.xml
If a user changes their background off of the default Lagoon, there's no way to change it back to lagoon without one of these entries.
I've tested this on my personal image (2nd screenshot), so porting the changes over to this repo.
Before:
After (hopefully):
=> fix: Create gnome settings background entry

usr/bin/ublue-nix-install
You discussed to change the initially proposed dir name from /opt/nb to /opt/nixbackup ... code got committed using both, in an inconsistent manner.
=> fix: inconsistent dir naming in PR #152

README.md
1. Markdown bullet list max indent seems to be 3 spaces, was 4 spaces -> list got folded into a single paragraph, which was probably not your intent.
2. Must delete the source keyfile (not the compiled file), otherwise it gets just recompiled again on dconf update.
=> docs: Fix formatting, fix dconf reset instructions.

Containerfile
Reverts ublue-os/bluefin#174
These files aren't the issue triggering gnome-software so revert this.
=> Revert: "fix: remove extra repo files from final image"

etc/yafti.yml
This _should_ just handle it in the background so gnome-software doesn't ask.
=> fix: add thirdparty disable

Containerfile
This patch removes the fixed install of fleek in preparation for the upcoming version which must be installed via nix flake.
=> fix: remove fixed fleek verion

.github/workflows/build.yml
Works in main, propagating here.
Co-authored-by: xnasero@posteo.net
=> chore(ci): refactor: avoid subshell, sign image with env. var

packages.json
It's included in main already, no need to have it here.
=> fix: remove podman-compose from image

Containerfile.toolbox
Fixes comment https://github.com/ublue-os/bluefin/pull/198#pullrequestreview-1407080950
The Containerfile is trying to install packages from a non-existent `extra-packages` file, so this PR changes to `toolbox-packages`
=> fix: copy toolbox-packages file during build

toolbox-packages
just and vimdiff aren't in ubuntu
=> fix: update toolbox-packages

.github/workflows/build-toolbox.yml
This would end up being ublue-os/ubuntu-toolbox, which reads nicer
=> chore(ci): use different naming convention

etc/dconf/db/local.d/01-ublue
GNOME has separate shortcuts for switching windows and applications.
Application switcher by default shows grouped windows from all workspaces.
Windows switcher doesn't group windows and by default shows only windows with small previews only from the current workspace.
Originally GNOME doesn't bind shortcuts to "switch-windows" so "switch-applications" are used for both Super+Tab and Alt+Tab
When user binds Alt+Tab to "switch-windows" , "switch-applications" gets unbind for some reason.
So Ubuntu settings bind both.
=> Switch windows (not applications) with Alt+Tab

etc/distrobox/distrobox.ini
New feature in distrobox, this will let us declare toolboxes. This feature is unreleased so we're just prepping for it.
=> feat(toolbox): add distrobox.ini for ubuntu image

Containerfile, workarounds.sh
Yanking this from the nvidia image, this makes ld work so we can have nice things.
=> feat(dx): add ld workaround

etc/yafti.yml
GNOME Games is EOL and unmaintained, and Lutris should cover most of the same use cases and more.
=> feat: replace GNOME Games with Lutris

Containerfile, usr/share/ublue-os/just/custom.just
I'll make the justfile framework-specific later.
=> feat: add a quick stress-ng benchmark

framework/etc/tlp.conf
Update the tlp.conf file after following framework's optimization instructions https://knowledgebase.frame.work/en_us/optimizing-fedora-battery-life-r1baXZh
Frequency settings are probably processor-specific. This one is modeled on an i7-1165G7 @ 2.80GHz.
=> feat(framework): ship framework-optimized tlp.conf

Containerfile, dx/etc/dconf/db/local.d/01-ublue-dx
Today, UbuntuMono Nerd Font is installed but not the standard Ubuntu font. This adds the Nerd Font version to the DX image and sets it as the default for the desktop
=> feat: use Ubuntu Nerd Font for DX images

Containerfile
Closes #237 
This PR installs the latest release of DevPod and DevPod CLI.
There's a known issue with DevPod where there's some permission issues, but hopefully they will be resolved soon and DevPod will work as expected.  DevPod still works using one of the other providers though - it's just the Docker provider that's broken.
On my personal image, I've installed Docker in the meantime, which works well with DevPod.  I get that we don't want Docker on these images though.
Upstream issue: https://github.com/loft-sh/devpod/issues/413
=> feat(dx): install devpod and devpod cli

dx/etc/dconf/db/local.d/01-ublue-dx, dx/etc/distrobox/distrobox.ini, etc/dconf/db/local.d/01-ublue, etc/distrobox/distrobox.ini
Closes #265 
The only thing it could break is the existing Ubuntu distrobox shortcut, but the `flatpak run` command works locally, so I don't see how it could fail.
This PR creates a new custom keybinding to open up a Fedora distrobox with BlackBox using <kbd>CTRL</kbd> + <kbd>ALT</kbd> + <kbd>F</kbd>.  
It also refactors the existing Ubuntu keybinding to call distrobox directly, rather than opening the BlackBox app and hoping the initial command remains the same.
=> feat(dx): open fedora userspace on shortcut

dx/etc/dconf/db/local.d/01-ublue-dx
I forgot to actually register the Fedora Distrobox keyboard shortcut in dconf after adding it, so the shortcut did nothing.
This PR registers the keybinding.
Since the Fedora shortcut is only in the dx image, I copied the entire `org/gnome/settings-daemon/plugins/media-keys` over to the dx file.
=> fix(dx): register fedora distrobox shortcut

etc/dconf/db/gdm.d/01-ublue, etc/dconf/profile/gdm
This complements commit 8c0d9ae
Based on:
- https://help.gnome.org/admin/system-admin-guide/3.38/login.html.en#appearance
- GDM Settings
=> Enable "tap-to-click" for GDM

toolboxes/packages.wolfi
Reverts ublue-os/bluefin#316
This conflicts with `procps`, which doesn't get installed until you create a distrobox, causing a fatal error.
=> fix: revert "feat(wolfi): add uutils"

Containerfile
These are ugly and make no sense in the menu.
=> fix: hide icons for CLI apps

toolboxes/packages.ubuntu
This should help with launch time. And drop npm for size.
=> feat(ubuntu): add libvte and bc since distrobox needs it

Containerfile
We don't need all this stuff in the vanilla image
=> feat: move developer-centric things to -dx

Containerfile
Their latest release[^1] change the naming scheme, so the build is currently broken.
[^1]: https://github.com/loft-sh/devpod/releases/tag/v0.3.1
=> fix: adapt to new devpod artifact name

Containerfile
container based systems can't have cockpit-ws installed locally, it must be run by podman. This change removes the cockpit-ws package.
https://cockpit-project.org/running#coreos
=> fix: remove host installed cockpit-ws

Containerfile, usr/share/ublue-os/just/custom.just
re-add cockpit-ostree plugin
add `just cockpit` in custom.just to enable and start podman cockpit-ws service
=> feat: add cockpit-ostree, add just cockpit command

usr/share/ublue-os/just/custom.just
Adds a just command `code-profile` that imports the bluefin-dx vs-code profile that enables dev container development.
=> feat: import vscode profile for container development

usr/share/ublue-os/just/custom.just
=> feat(just): add a wolfi OS distrobox shortcut

artifacthub-repo.yml
So that we can show up as a verified publisher.
=> chore: add artifact hub information

packages.json
We can finally remove this again, gnome-software renders the store stuff just fine now without this. Goodbye!
=> fix: remove gnome-software-rpm-ostree

Containerfile
Turns out this change was still needed, previous testing tainted by bad methodology. Apologies for the issues.
=> fix: Restore VRR functionality after update

Containerfile
This PR will replace the Silverblue text with Bluefin in the os-release file. This is only replaced on the PRETTY_NAME line. 
Which results in a grub menu showing like the image below:
As a side result the about page in gnome-settings will also show this name.
If this is allowed, and merged an then maybe picked up by ublue-main image to do the same. We need to change this to match their name of choice. That is something to remind.
=> fix: Show as Bluefin in grub menu

packages.json
add the monitor database so we aren't stuck with 10 year old monitor configs
=> fix: add ddccontrol-db for monitor database

Containerfile
In #31 the cleanup was removed, probably because the repo was commented out. It is now used again, so let's clean it up after everything is installed. To be sure it didn't got lost again in the future I've placed it right below, so it is grouped.
=> fix: cleanup gnome-vrr repo

usr/share/ublue-os/just/custom.just
Adds target to `usr/share/ublue-os/just/custom.just` to install [aqua](https://aquaproj.github.io)
Results from testing:
```
$ just
=> Installing aqua ...
pushd "$(mktemp -d)"
/tmp/tmp.14Op44xUmE ~
curl -sSfL -O https://raw.githubusercontent.com/aquaproj/aqua-installer/v2.1.1/aqua-installer
echo "c2af02bdd15da6794f9c98db40332c804224930212f553a805425441f8331665  aqua-installer" | sha256sum -c
aqua-installer: OK
chmod +x aqua-installer
./aqua-installer
===> Installing aqua v2.2.3 for bootstraping...
===> Downloading https://github.com/aquaproj/aqua/releases/download/v2.2.3/aqua_linux_amd64.tar.gz ...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-- …
```
=> feat(just/custom): add aquaproj install target

usr/share/ublue-os/just/custom.just
This change adds a recipe to the custom justfile that modifies the user's shell rc files to append homebrew eval script if it doesn't already exist.
=> feat: add brew-config recipe to modify user rc

usr/share/ublue-os/just/custom.just
Current implementation left over an `aqua-installer` binary because it didn't change into the tmp dir that was created.  
Resulting in behavior like this:
```
[user@fedora ~]$ ls aqua-installer
ls: cannot access 'aqua-installer': No such file or directory
[user@fedora ~]$ just aqua 
=>Installing aqua ...
--- SNIP ---
[user@fedora ~]$ ls aqua-installer
aqua-installer
[user@fedora ~]$ 
```
Now it behaves like it should:
```
[user@fedora ~]$ ls aqua-installer
ls: cannot access 'aqua-installer': No such file or directory
[user@fedora ~]$ just aqua 
=>Installing aqua ...
--- SNIP ---
[user@fedora ~]$ ls aqua-installer
ls: cannot access 'aqua-installer': No such file or directory
[user@fedora ~]$ 
```
=> fix(just): fix aqua-installer

usr/share/ublue-os/just/custom.just
should resolve errors if zsh isn't installed when running `just brew-shell`
=> fix: just brew-shell will create .zprofile and .bash_profile if needed

usr/share/ublue-os/just/custom.just
just zsh and just fish had params out of order
=> fix: flag order for just shells

usr/share/ublue-os/just/custom.just
Fixes #274 
This checks the current booted image. Based on that it let you switch to a dx variant or back to normal with:
```
just devmode-on
just devmode-off
```
Tested on all the images. 
```
bluefin
bluefin-dx
bluefin-nvidia
bluefin-dx-nvidia
bluefin-framework
bluefin-dx-framework
```
=> feat(just): add devmode-on/off

Containerfile
Remove podman-docker so each user as the ability to choose to install moby-engine if desired
=> fix: remove podman-docker

usr/share/ublue-os/just/custom.just
fixes #408 
and updates Nix to Determinate Systems installer (hooray!)
=> fix: update nix installer, fix broken just shell script

toolboxes/Containerfile.ubuntu, usr/share/ublue-os/just/custom.just, usr/share/ublue-os/quadlets/podmansh.container
- passes in passwd/group
- passes in selinux
- adds passwordless sudo to the toolbox
- adds a "stop" command when running `just podmansh` in case it was already running (should only run into this while debugging or messing around, not really common)
=> fix: podmansh improvements

usr/share/ublue-os/just/custom.just
When running `just nix-devbox-global` it echoes the commands to run to configure your `bash` or `zsh` shell but the devbox scripts are misnamed: `bash/zsh` < - > `hook`
```
$ devbox global run install-bash-hook
/var/home/robin/.local/share/devbox/global/default/.devbox/gen/scripts/.cmd.sh: line 3: install-bash-hook: command not found
$ devbox global run install-zsh-hook
/var/home/robin/.local/share/devbox/global/default/.devbox/gen/scripts/.cmd.sh: line 3: install-zsh-hook: command not found
```
=> fix(just): devbox global shell hooks

etc/dconf/db/local.d/01-ublue
This disables the `use-custom-command` setting from Blackbox. Setting it to true would block the use of any other custom command. So it would not been able to launch `flatpak run com.raggesilver.BlackBox --command "distrobox enter fedora"` for example.  Which is used for the fedora userspace shortcut.
This also means it added back the `--command "distrobox enter ubuntu"` to the ubuntu userspace shortcut, as it would otherwise launched a host system Blackbox.
=> fix: fedora userspace shortcut

Containerfile
Upstream split mutter into `mutter` and `mutter-common` -- modify install line for GNOME VRR to also replace `mutter-common`.
=> fix: Replace new mutter-common package

dx/etc/dconf/db/local.d/01-ublue-dx, dx/usr/bin/bluefinbox-enter
Fixes #383 
Add a wrapper script for entering non default boxes like fedora. `distrobox enter` will default to the ubuntu image so that shortcut don't have to be changed. 
In short it adds a script to see if the box exists locally, otherwise it assembles it first. At this moment it will assemble all the boxes in the `distrobox.ini` manifest. Upstream merged code for acting on a specific box in the manifest. So when a new version of distrobox is released it will be possible to assemble only the container that we want to enter.
=> fix(dx): use distrobox-enter wrapper for non default images

toolboxes/packages.fedora
Adds `pinentry` to the `fedora-toolbox` 
Improves first run startup time of the box alot.
=> fix(toolbox): add missing package to fedora

usr/etc/systemd/system/multi-user.target.wants/dconf-update.service
Since the systemd/system-preset enabled, but didn't create the target.wants symlink, we may need this to ensure the service starts as is expected.
=> fix: force enable dconf-update service via symlink

Containerfile
I guess there were two places in the Containerfile where this layer was being added.
=> fix: remove 2nd cosign layer since upstream provides in RPM

Containerfile, build.sh, packages.json
This uses a new introduced `ARG PACKAGE_LIST` to define which image we are building, and take the corresponding packages out of `packages.json`. Includes and excludes all work like before, just a slighty more narrowed down approach to make it work with the bluefin build proces.
Fixes: #276
=> fix: make use of packages.json for all images

.github/workflows/build.yml
We are not using `IMAGE_NAME` in our `Containerfile` anymore after PR #457.  
Because it was still passing that as a build argument. It would lead to the following warning while building the images. `Warning:  one or more build args were not consumed: [IMAGE_NAME]` 
This PR removes it from the `build-args` and should give us a clear build without warnings.
=> fix: remove not consumed build arg

usr/share/ublue-os/just/custom.just
Improved version of the `just jetbrains-toolbox` command. This should now always install the latest version without us having to specify it.
=> fix(just): improve JetBrains Toolbox installation

usr/etc/yafti.yml
This makes it easy to hide .desktop apps, so people can hide things they don't want.
=> feat: add pinapp menu editor

usr/etc/yafti.yml
Defaults are still exactly the same, just reorganized a bit to be more readable, atleast in my opinion. Feel free to merge it or not, and if there are any questions, im always open to change things up. :)
I also added an alternative Steam Proton Updater, which is made in GTK, so it fits the desktop quite a bit better. The Tool added is here: https://flathub.org/apps/com.vysp3r.ProtonPlus
=> feat: Reorganizing Yafti with new submenus

usr/etc/yafti.yml
Adds a  link to the Discussions and Announcements page on the final screen.
=> fix(yafti): add link to announcements and discussions

usr/etc/yafti.yml
Fixes #471 
Moves the core apps to a seperate "required applications" screen like images below:
=> fix(yafti): move core apps to seperate screen

Containerfile
We used terra repo for our nerd fonts, but lately their repo is very unstable which resulted in lots of failing builds. I've forked their spec repo and set the specific nerd-fonts.spec up on copr. This should save us some from failing builds.
The spec I used is available here:
https://github.com/bobslept/terra-packages-specs/blob/f38/anda/fonts/nerd-fonts/nerd-fonts.spec
And the copr:
https://copr.fedorainfracloud.org/coprs/bobslept/nerd-fonts/
=> fix: switch to copr for nerd-fonts

Containerfile, packages.json
to avoid issues of certain flatpaks (like steam) not showing CJK fonts properly.
How its looking without this patch:
how it looks with the patch:
it could also potentially need a fc-cache flush. in case of it not working from the get go. the fontconfig folder must be nuked in `/var/home/$USERNAME/.var/app/com.valvesoftware.Steam/cache/fontconfig` and recreated with `flatpak run --command=fc-cache com.valvesoftware.Steam`
=> fix: Add proper cjk fonts

usr/share/ublue-os/just/custom.just
This destroys pets and reassembles them as cattle, and then uses bootc upgrade. Layered packages currently not supported via bootc upgrade.
=> feat: add a declarative update command

packages.json
wl-clipboard offers similar functionality to xclip, but for Wayland users.
The specific reason I need wl-clipboard is to use the Image Paste extension for Visual Studio Code. It allows you to quickly paste images into Markdown files. Plus, I'd like to be able to copy and paste files from the terminal.
=> Add wl-clipboard to installed packages

toolboxes/Containerfile.fedora, toolboxes/packages.fedora
Base our fedora toolbox of ublue-os/fedora-distrobox that is already optimized for distrobox usage.
=> feat(toolbox): base fedora of ublue fedora-distrobox

packages.json
This has support in gnome 45 now so I wanna try it. It's by the folks who did barrier:
https://github.com/input-leap/input-leap
=> feat: add input-leap

usr/share/ublue-os/just/60-custom.just
These just commands will be shipped via the framework repo. No need for them in here anymore.
=> fix: remove framework related just kargs

Containerfile, image-info.sh
Generates information specific to the image being built. This is used for auto-signing via ublue-update but also has other practical purposes such as distuingishing which flavor or base may be in use
=> feat: Generate image info for auto-signing via ublue-update

image-info.sh
Currently `ostree-image-signed` isn't included in `image-info` which bricks the system update function of `ublue-update`, as it is unable to rebase to an image without the prefix
=> fix: use proper image ref for generating image info

packages.json
This is a dupe and we prefer gnome-extensions-manager anyway.
=> fix: remove gnome-extensions-app

Containerfile
Proposed change:
* I can add multiple *.just files into the just/ folder, in addition to the core custom.just file.
* At build time, all *.just files are concatenated together. The new `find` command in the Containerfile makes sure that content is separated by 2 newlines, so that a possibly missing newline at the end of an individual file cannot break justfile syntax.
PS: I roll my own slightly changed image off ublue-os/bluefin. I prefer extending functionality by adding extra files, instead of mangling with existing core files. This proposed change enables that.
Usage example: https://github.com/hirnidrin/bluefin/tree/8bfb7a35cbe0503f6f8fabda581368fdd1939304/just
=> feat: Allow multiple justfiles.

build.sh
The includes and excludes are handled a bit oddly in the old build.sh pattern.
This change always does the requested installs, but then always does the override remove for excludes, which enables excluding dependancies of packages which were just requested to be installed.
This should cause #519 to work as expected.
=> fix: tweak build.sh handling of package.json

packages.json
Application didn't get removed because of a typo
=> fix: typo in gnome-extensions-app

just/custom.just
Just is currently broken because of an indentation error. 
```
just
error: Unknown start of token:
|
349 | /opt/notebooks && /opt/conda/bin/jupyter notebook \
|                                                   ^
```
This should be fixed now.
=> fix(just): pytorch intendation

build.sh
This is an addtion to PR #525 which maintains the goal of that PR, allowing for packages installed as a depdency to be later excluded, but also fixes the bug which was inadvertently created.
=> fix: ensure that package override replace works properly

dx/usr/etc/profile.d/vscode-bluefin-profile.sh, dx/usr/etc/skel.d/.config/Code/User/settings.json
This PR contains a part of #285 and will ship a default `settings.json` based on the settings from `just vscode-profile`
It will only set it when there is no existing version of `settings.json` so it will not change it when there is already a config. 
I was unable to figure out how to ship default extensions that where used in `just vscode-profile`
=> feat: ship default vscode settings.json

.github/workflows/build.yml
Shortens it up to make reading the builds easier, and bazzite already did this so a win for consistency too.
=> chore(ci): rename job title to make

Containerfile, packages.json
This PR adds the service and enables the timer, but does nothing to the built in rpm-ostree updater.
=> feat: Add ublue-update service

.github/workflows/build.yml
We removed the build-arg IMAGE_NAME earlier in PR #458  to suspress a not consumed argument. This argument is now used for `image-info.sh` but we didn't pass it in again. This leads to an empty image-name:
```
cat /usr/share/ublue-os/image-info.json
{
"image-name": "",
"image-flavor": "main",
"image-vendor": "ublue-os",
"image-ref": "ostree-image-signed:docker://ghcr.io/ublue-os/",
"image-tag":"latest",
"base-image-name": "",
"fedora-version": "38"
}
```
Which then fails the new ublue-update service.
```
Oct 01 12:26:07 fedora ublue-update[6147]: [2023-10-01 12:26:07,221] ublue_update.cli:ERROR | /etc/ublue-update.d/system/00-system-update.sh returned error code: 1
Oct 01 12:26:07 fedora ublue-update[6147]:                         Program output:
Oct 01 12:26:07 fedora ublue-update[6147]: …
```
=> fix: pass IMAGE_NAME build arg for image-info.sh

Containerfile
While we fix up the other stuff.
=> fix: turn off update service

usr/bin/ublue-system-flatpak-manager, usr/bin/ublue-system-setup
This PR makes a few changes to the order of operations on the new Flatpak services, to ensure users are not left without packages if the script fails part way through.
It removes duplicate fedora flatpak repo removal
It deletes Fedora flatpaks in the new manager service
It moves destructive fedora flatpak changes to after new packages are installed to ensure user is not left without packages
I would still like to use file hashes to determine whether these scripts should be ran again or not, but this works for now.
=> fix: make removing flatpaks a little safer

usr/etc/dconf/db/local.d/01-ublue
This worked out nicely instead of adding a dock-specific -dx section. If you're on the dx image this shows up, if not then it just doesn't show up.
=> feat: add vscode and distrobox to dock if installed

usr/bin/ublue-system-flatpak-manager
Disables the system variant of the flathub flatpak repo. This way gnome-software will always prefer user flatpaks instead of system ones.
=> fix: disable system flathub

Containerfile
The ublue-update service now rebases the unsigned images the correct way by preserving the installed tag. Tested on two fresh installed VM's. Output below after running the service.
```
Deployments:
ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:38
Digest: sha256:b6f9f6a8f9ef134fcc4a7634a652f764b54976af1f29ae0c766557a3c95fb695
Version: 38.20231003.0 (2023-10-03T19:29:48Z)
● ostree-unverified-registry:ghcr.io/ublue-os/bluefin-dx:38
Digest: sha256:b6f9f6a8f9ef134fcc4a7634a652f764b54976af1f29ae0c766557a3c95fb695
Version: 38.20231003.0 (2023-10-03T19:29:48Z)
```
```
Deployments:
ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:38
Digest: sha256:b6f9f6a8f9ef134fcc4a7634a652f764b54976af1f29ae0c766557a3c95fb695
Version: 38.20231003.0 (2023-10-03T19:29:48Z)
● …
```
=> fix: enable ublue-update

usr/etc/dconf/db/local.d/01-ublue
Additional dconf value is needed for it to work (thanks to Akzel)
=> fix: Assure that "Sort folders first" default in Nautilus applies

usr/etc/ublue-update/ublue-update.toml
Ship a default config for ublue-update. Ignoring the battery levels and disables the notifications.
=> feat: ship ublue-update default config

Containerfile
When the rpm is installed, it overwrites the config file we deliver. To avoid this, first copy the config to /tmp and from there put it in the system after the rpm is installed.
=> fix: avoid ublue-update.toml being overwritten

usr/etc/dconf/db/local.d/01-ublue
Should fix #564 
We missed some forward slashes, which leads to segfaults in `gsd-media-keys`. This only happend on bluefin, the bluefin-dx shortcuts where good.
=> fix: typos in keyboard shortcut

Containerfile
Gives us time to telegraph needed supporting changes downstream.
=> fix: Only enable ublue-update on F39 builds

toolboxes/Containerfile.wolfi
Should fix #560 
Still produces warnings `Warning: there was a problem setting up the user` but the distrobox seems usable again.
=> fix(toolbox): wolfi package conflict

just/custom.just
/var/home should be used rather than /home
=> chore: Make brew-shell just command more accurate

toolboxes/Containerfile.wolfi, toolboxes/packages.wolfi
Warning: Only works properly after first running `just distrobox-git`, see notes in Containerfile.wolfi
Fixes issue #560
Improves on PR #572
=> fix(toolbox): Cleanup wolfi container.

Containerfile
Let's get vrr installed for all versions, it should be compatible.
The checks where in there, but it only acted on non 39 builds to go in there. By removing the check at the top we give f39 builds a fair chance. 
And it seems to work out seeing the green builds. Perfect.
=> chore: actually enable gnome-vrr on f39 builds

usr/bin/ublue-system-flatpak-manager, usr/bin/ublue-user-flatpak-manager, usr/lib/systemd/system/ublue-system-flatpak-manager.service, usr/lib/systemd/user/ublue-user-flatpak-manager.service
In the current setup the flatpak-user-manager will always write a "lock" file, even if commands failed to run. 
The new version exits on an error so it will not write the lock file and it will try again later. 5 times via systemd and otherwise it tries again on reboot.
I removed the start install notification, because it will flood your notifications on retries and moved the finished notifcation right above the write of the lock file. 
And add the same changes to flatpak-system-manager too.
=> fix: flatpak-manager exit and retry on failure

usr/bin/ublue-system-flatpak-manager, usr/bin/ublue-user-flatpak-manager, usr/etc/flatpak/system/remove, usr/etc/flatpak/user/remove
After adding error checking in the flatpak-managers I've spotted two issues. 
Due to the new error check it will always fail if it wants to remove a package that does not exist on the system. This can lead to problems so I've removed the error check on removal.
Another thing I spotted (via the now removed error check) that we wanted to remove system flatpaks via the user remove list, which errors out. So I moved them to the system remove list.
Below an example of what was happening.
```
❯ flatpak remove --user org.gnome.Cheese
error: No installed refs found for ‘org.gnome.Cheese’
~ 
❯ flatpak remove --system org.gnome.Cheese
ID                     Branch       Op
1.     org.gnome.Cheese       stable       r
Proceed with these changes to the system installation? [Y/n]: n
```
You may ask …
=> fix: flatpak-manager may fail on removal

just/custom.just
This fixes #408 (`just fish` and `just zsh` failing). The problem (and the reason that #420 doesn't fix it) is because the `lchsh` command actually doesn't accept the new shell as a CLI argument at all!
Another way to do this (and continue using `lchsh`) would be to instead run the commands as, e.g., `echo /usr/bin/zsh | sudo lchsh $USER`, but this results in an empty (and thus slightly misleading) prompt being shown to the user:
```console
$ echo /usr/bin/zsh | sudo lchsh $USER
[sudo] password for bri: 
Changing shell for bri.
New Shell [/usr/bin/zsh]: Shell changed.
```
If we just use `usermod` it doesn't actually give any feedback, so I also threw in a little posix pipe to parse the shell back out of /etc/passwd after.
=> Use `usermod` instead of `lchsh` in custom.just

usr/bin/ublue-system-flatpak-manager
Currently when we remove system flatpaks from the fedora repo (which we replace with flathub ones). There is always one flatpak that doesn't get removed. That is `org.fedoraproject.Platform` which is the runtime for other applications. 
Because we currently remove them at the same time, the runtime will not be removed, because it is needed for apps which are not yet removed. 
```
flatpak list
Name                    Application ID                    Version        Branch        Installation
Fedora Platform         org.fedoraproject.Platform        38             f38           system
```
```
Uninstalling runtime/org.fedoraproject.Platform/x86_64/f38
Error: Failed to uninstall org.fedoraproject.Platform: Can't remove org.fedoraproject.Platform/x86_64/f38, it is needed for: …
```
=> fix: split flatpak app and runtime removal

usr/bin/ublue-system-flatpak-manager
Current setup works great if you only have one installed branch version, for example f38. But leads to problems when multiple are installed. 
```
flatpak remove org.fedoraproject.Platform
Similar installed refs found for ‘org.fedoraproject.Platform’:
1) runtime/org.fedoraproject.Platform/x86_64/f38 (system)
2) runtime/org.fedoraproject.Platform/x86_64/f39 (system)
3) All of the above
Which do you want to use (0 to abort)? [0-3]: 0 
```
This PR adds the branch and the arch of the runtime, so it knows which one to remove.
=> fix: handle removal of multiple branches of same runtime

usr/bin/ublue-system-flatpak-manager, usr/bin/ublue-user-flatpak-manager
Instead of running a single `flatpak install/remove` command for every package. Try use a single command with all the packages. This seems to improve the stability a lot. 
I've tried multiple fresh installs with this code. And every time I end up with the same  packages that are listed in the `flatpak/user/install` file.
=> fix: improve flatpak-manager to use less commands

.github/workflows/build.yml
Allows users to run one release behind the latest Fedora version without any intervention every major version upgrade
=> feat(ci): Introduce support for gts tag (tracks Fedora - 1)

.github/workflows/build.yml
Now that the Surface kernel is available on Fedora 39, these can be enabled
=> feat: Enable Fedora 39 Surface images

packages.json
Reverts ublue-os/bluefin#593
The COPR only builds GNOME 45+ versions, this should be 39 only.
=> revert: "feat: swap out tailscale extension"

Containerfile
Ticket: https://github.com/ublue-os/bluefin/issues/603
Installs VHS as an RPM package and ttyd as a binary.
ttyd is a requirement for VHS as it seems like VHS runs the terminal in a browser and records it.
=> feat(dx): Install charm vhs

Containerfile
adds `gum` from charm.sh for delightful scripting with prompts, pickers, selection boxes.
=> feat: add gum for scripting

just/custom.just
Add a nice message and ask the user to update their system first when needed to switch to the Developer Experience.
Instead of and error:
```
just devmode-on
Rebasing to a developer image
error: Old and new refs are equal: ostree-unverified-image:oci:/var/ublue-os/image
error: Recipe `devmode-on` failed with exit code 1
```
=> fix(just): add msg to devmode-on

Containerfile
Reverting DevPod to a build which includes an RPM due to the Loft.sh team switching to AppImages.
We will decide how to proceed shortly.
=> fix: revert DevPod to latest available RPM (v0.3.7)

Containerfile
I think this was not added on purpose and thus can be cleaned up. 
Or do we have the intention to ship steamdeck.rpm on our image and did I miss something?
=> chore: steamdeck rpm cleanup

just/custom.just
The `just docker` command didn't have a description when the user types `just` to list all the commands available.
=> chore(just): add docker description

Containerfile
Asus builds are currently failing, because it can't find the the evdi rpm to install. Because of conflicts with the asus kernel it is disabled in the akmods repo.
- https://github.com/ublue-os/akmods/pull/87
This PR will disable the installation of the evdi rpm on asus images.
=> fix: exclude evdi on asus

.github/workflows/build-fedora-toolbox.yml, .github/workflows/build-ubuntu-toolbox.yml, .github/workflows/build-wolfi-toolbox.yml, .github/workflows/build.yml
Yesterday I noticed when I made a typo, and pushed a commit into my PR, the actions keep on running. Which make no sense when there is a new commit, and with 28 images builds per commit, the queue would be pretty full after a few commits. Building stuff that doesn't matter anymore. 
I've found the following documentation and tried to implement it on my personal fork to see if this would work. 
https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
It did work perfect, so I would like to try it out here. If this works good here, it would definitely  something to implement for other repo's building a lot of images to keep the queue clean.
Hope it works out as intended here, it would be a big improved. If not …
=> chore(ci): improve queue by canceling jobs

just/custom.just, usr/share/ublue-os/quadlets/podmansh.container
- enable podman socket in user space and mount it into the quadlet container
- additional documentation on how to improve vscode experience with podmansh
- call out the environment variable needed within podmansh container for dind/pinp
- map in linuxbrew container so brew is inside and outside podmansh
- other random things that I changed to get a nice experience locally :upside_down_face:
=> feat: update quadlet to pass socket in, add additional documentaiton

.github/workflows/build.yml
Integrate our new [just syntax checker](https://github.com/ublue-os/just-action) into the build action.
=> feat: add just syntax checker

usr/etc/dconf/db/local.d/01-ublue
This still appears to be problematic for some users, so let's just shut it off by default. The new `just gnome-vrr` is still there for people who want to opt in.
=> fix: turn off gnome vrr by default

just/custom.just
Seems that brew related just commands are now available globally
- https://github.com/ublue-os/config/pull/158
=> chore(just): brew moved to config repo

just/custom.just
Instead of using `just devmode-on` or `just devmode-off` the user can now do `just devmode` and enable/disable it.
=> feat(just): combine devmode on/off with gum

packages.json
virt-viewer is required to connect to spice consoles for incus and lxd virtual machines.
=> fix: add missing virt-viewer for -dx

dx/usr/bin/bluefinbox-enter
With distrobox 1.6 entering stable soon, we are able to assemble a distrobox specified by `--name` instead of assembling them all at once. This means when hitting the keyboard shortcut for entering a fedora distrobox it will only assemble the fedora one.
~As long as distrobox 1.6 is not in stable leave this as draft.~
distrobox 1.6 is now available on the image, so this can be merged.
`distrobox-1.6.0.1-1.fc39.noarch`
Follow up on 
- https://github.com/ublue-os/bluefin/pull/439
=> fix(dx): improve distrobox-enter wrapper

toolboxes/packages.ubuntu
Adds a missing dependency on the startup of the ubuntu container when launched with distrobox. This avoids the need of installing it when opening the box the first time.
=> fix(toolbox/ubuntu): add missing distrobox dependency

.github/workflows/build.yml
In some situations the general `Check all builds successful` will be skipped. There for it is possible that the required check in the PR will be ignored, even if a build is not build successful.
This implementation will ensure that the check is always run, unless it is canceled. When it runs it checks the result for failure. 
It should only turn green if all builds are green.
=> fix(ci): never skip successful builds check

just/custom.just
This adds an easy install command for [garden.io](garden.io), a Cloud Native tool enabling portable pipelines, ephemeral Kubernetes clusters, powerful remote K8s workflows, templating and more.
Disclaimer: I am the Head of DevRel at [garden.io](garden.io).
=> feat(just): add garden.io

just/custom.just
Cleaner on the prompt if it's named this way.
=> fix(just): name bluefin-cli -> bluefin

Containerfile, packages.json
Adds the package `kcli` to the `bluefin-dx` variant.
Docs: https://kcli.readthedocs.io/en/latest/#package-install-method
Copr used: https://copr.fedorainfracloud.org/coprs/karmab/kcli/
Fixes: #720
=> feat(dx): add kcli

packages.json, usr/etc/dconf/db/local.d/01-ublue
Split off from the Prompt PR, this is the LogoMenu and Nautilus extension changes only, with any prompt-specific changes removed.
=> feat: Add Logo Menu & Prepare for Prompt future

usr/bin/ublue-system-flatpak-manager, usr/bin/ublue-user-flatpak-manager
Someone may choose to install a flatpak on the removal list intentionally, in which case we don't want to forcibly remove it
This verifies the version file exists following a successful run and skips the removal process if it does
=> chore(flatpak-manager): Only remove flatpaks a single time

Containerfile, dx/usr/etc/dconf/db/local.d/01-ublue-dx, packages.json, usr/bin/xdg-terminal-exec, usr/etc/dconf/db/local.d/01-ublue, usr/etc/flatpak/user/install
Adds Prompt Integration via nautilus-open-any-terminal, and xdg-terminal-exec.
=> feat: Add Prompt integration

Containerfile, packages.json
Allows us to continue shipping an up-to-date RPM for DevPod on DX images.
=> feat(dx): Use DevPod from the ublue-os/staging copr

packages.json
Adds distrobuilder to -dx for building custom incus and lxd images.
=> feat: add distrobuilder to -dx

usr/etc/dconf/db/local.d/01-ublue
=> fix: Restore Control+Alt+T shortcut for terminals

.github/workflows/build.yml
Validates the integrity of the base image being built from, and the Chainguard images in DX, via cosign before continuing to build. Ensures we only build with signed images
=> feat(ci): Verify base/Chainguard image(s) with cosign before building

usr/etc/dconf/db/local.d/01-ublue, usr/share/X11/xkb/symbols/capslock
This is one of the 1st issues which ex-Windows users notice when they switch to Linux. I am one of those users who uses Caps-Lock instead of Shift for uppercase letters.
This will get rid of input delay, while the "light indicator" delay is still the same (I mentioned this distinction to not confuse you if you don't "see" any changes).
To test, type "Helo" repeatedly & quickly using Caps Lock.
You will no longer see "HElo" in your texts.
Fix took from here:
https://forum.manjaro.org/t/caps-lock-behaviour-wayland/79868/8
=> feat: Fix caps-lock input delay

toolboxes/Containerfile.bluefin-cli, toolboxes/files.bluefin-cli/etc/pam.d/sudo, toolboxes/files.bluefin-cli/etc/pam.d/sudo-i, toolboxes/files.bluefin-cli/etc/sudoers
Enables sudo in the bluefin-cli.  It also chowns the linuxbrew files to UID 1000. This makes the assumption that the user has UID 1000.
For whatever reason, the groups are not generated correctly for the user so we cannot reuse adm/wheel. The only valid group for the user is their own. Since most users are user 1000, we can assume this is the case. If they are not, they will have to use the su-exec method that already exists to change /etc/sudoers and chown linuxbrew.
=> feat: bluefin-cli enable sudo/chown linuxbrew

Containerfile
Timothée Ravier from RedHat has informed us that running both Podman and Docker can result in unexpected behaviour.  
This PR does not start the Docker service by default, but whenever someone interacts with the socket (e.g. `docker container ls`) the `docker.service` unit will be started automatically.  This seems to replicate the current CoreOS behaviour.
> It is worth noting that in Fedora CoreOS we have docker.service disabled by default but it is easily started if anything communicates with the /var/run/docker.sock because docker.socket is enabled by default. This means that if a user runs any docker command (via sudo docker) then the daemon will be activated.
[Source](https://docs.fedoraproject.org/en-US/fedora-coreos/faq/#_can_i_run_containers_via_docker_and_podman_at_the_same_time) …
=> fix: start docker.service on-demand instead of on-boot

just/custom.just
The `docker.service` unit is enabled when the user interacts with the `docker.socket`, so we do not need to explicitly start docker on boot.
=> fix: remove `systemctl enable docker` from `just docker` command

Containerfile, dx/usr/bin/bluefin-dx-groups, dx/usr/lib/systemd/system/bluefin-dx-groups.service, just/custom.just
Run a onetime service to add members of the wheel group to docker, incus-admin, lxd , and libvirt groups.
Removed just docker and replaced with just dx-groups to add the current user to docker, incus-admin, lxd, libvirt groups
=> feat(dx): Add wheel users to docker,incus-admin,lxd,libvirt groups

toolboxes/Containerfile.bluefin-cli
Adds Distrobox-host-exec and host-spawn in the build process.
Creates symlinks for running host level things on the host.
=> feat(bluefin-cli): Add host-spawn and create symlinks

toolboxes/Containerfile.bluefin-cli
Alpine based distros do not have merged /usr.
Fedora changed distrobox-host-exec to have #!/usr/bin/sh as the shebang instead of #!/bin/sh which results in distrobox-host-exec not working on unmerged /usr. This fixes it for bluefin-cli.
=> fix(bluefin-cli): Make sure /usr/bin/sh exists

.github/workflows/build-fedora-toolbox.yml, .github/workflows/build-ubuntu-toolbox.yml
Verifies the Ubuntu toolbox as well as the Fedora distrobox before building them.
All containers used in Bluefin are now verified!
=> feat(ci): Verify remaining toolboxes

.github/workflows/build-bluefin-toolbox.yml, .github/workflows/build-fedora-toolbox.yml, .github/workflows/build-ubuntu-toolbox.yml, .github/workflows/build-wolfi-toolbox.yml, .github/workflows/build.yml
I do not believe this flag is necessary.  If someone knows the origin of this, and we still need it, happy to close this PR.
> When transferring data among networked systems, trust is a central concern. In particular, when communicating over an untrusted medium such as the internet, it is critical to ensure the integrity and the publisher of all the data a system operates on. You use Docker Engine to push and pull images (data) to a public or private registry. Content trust gives you the ability to verify both the integrity and the publisher of all the data received from a registry over any channel.
=> fix: remove `--disable-content-trust` push flag

Containerfile
We'll save the alias for later
=> feat: add topgrade

just/custom.just, toolboxes/Containerfile.bluefin-cli, toolboxes/brew_script.bluefin-cli, toolboxes/files.bluefin-cli/brew_script.bluefin-cli
Persist the state of Homebrew's Cellar for #768
If the Cellar does not exist. It will be created in the User's home under $XDG_DATA_HOME. It is then volume mounted into the container making it accessible on any distrobox enter for the container.
This will relink all packages and reinstall explicitly installed homebrew packages.
=> feat(bluefin-cli): Persist State of Cellar

usr/etc/flatpak/user/install
I was hesitant to open this because of this [PR](https://github.com/ublue-os/bluefin/pull/790).  However, I am interested if anyone would like this application preinstalled on Bluefin.
I added this back in October to Bazzite.  I'm not sure if this meets the project's goals, but it allows users to manage their Flatpaks.
This includes:
- Opening the userdata (~/.var/app/...) directory for each application
- Downgrading applications
- Disabling updates for applications
- Creating snapshots of userdata for backups
This management is usually done with the command line, but this is simplified with this GUI application (similar to Flatseal for permissions).
It also will warn users if a Flatpak installed is using an end-of-life runtime.  
Project page: https://github.com/flattool/warehouse
=> feat: Add Warehouse

usr/etc/dconf/db/local.d/01-ublue, usr/etc/dconf/db/local.d/02-bluefin-folders
I cleaned up the commits and opened a new PR, just with the folders.
=> feat: add gaming, gamingutilities, utilities folders in gnome

just/custom.just, toolboxes/Containerfile.bluefin-cli, toolboxes/files.bluefin-cli/etc/pam.d/sudo, toolboxes/files.bluefin-cli/etc/pam.d/sudo-i, toolboxes/files.bluefin-cli/etc/profile.d/bluefin-cli-brew-firstrun.sh, toolboxes/files.bluefin-cli/etc/sudoers
Remove brew_script. Have logic in /etc/profile.d
Have sudo for UID 1000 in Containerfile.
=> chore: Cleanup bluefin-cli

.github/workflows/build.yml
The new contributor action is failing due to lack of permissions.  Now providing write access so it can update the README.md
=> fix: provide build workflow with write permissions to the repo contents

toolboxes/packages.wolfi
Wolfi build fails since 2 days due to a libcap version confilict originating from chainguard. distrobox init needs libcap -> every chainguard image building on wolfi-base is affected when trying to use it with distrobox.
```
ERROR: unable to select packages:
libcap-2.68-r0:
conflicts: libcap-2.69-r1
libcap-2.69-r1[so:libcap.so.2=2]
satisfies: world[libcap]
iputils-20231222-r0[so:libcap.so.2]
libcap-2.69-r1[so:libpsx.so.2]
libcap-2.69-r1:
conflicts: libcap-2.68-r0
libcap-2.68-r0[so:libcap.so.2=2]
satisfies: world[libcap]
iputils-20231222-r0[so:libcap.so.2]
```
Temporary fix: Pin libcap=2.68-r0 until this is sorted out upstream.
=> fix: Make Wolfi build again.

usr/etc/dconf/db/local.d/01-ublue
`dconf update` throws an error and stops compiling if quotes are missing.
=> fix: Add missing quotes to dconf string value.

Containerfile, packages.json
This will require the existing nerd-fonts package to be removed from ublue-os/staging before being merged.
=> feat: Switch to much smaller nerd-fonts package

Containerfile, motd/bluefin.md, motd/dracula.json
=> feat: add user-motd banner

Containerfile, just/custom.just, usr/lib/systemd/user/bluefin-cli-update.service, usr/lib/systemd/user/bluefin-cli.target, usr/share/ublue-os/bluefin-cli/bluefin-cli.sh
Get quadlet from toolbox repo. Have target for not having quadlet always run.
Modify `ujust bluefin-cli` to be more of a setup script. Only limited to bluefin-cli container right now.
TODO: move bluefin-cli logic to it's own script instead of having everything inside of our just script.
=> feat: Initial Container wireup

just/custom.just
The recipe for mlbox accidentally used the Assemble argument order (action, file, container/name) similar to the `distrobox assemble` command, instead of the AssembleList order (file, action, name) which is "Assemble a list from `file` we want to `action` from and `name` just just a quick selection"
This fixes #842
=> fix(just): correct the arg order for AssembleList when making mlbox

usr/bin/ublue-system-flatpak-manager, usr/bin/ublue-user-flatpak-manager
fix: Set priority of user flathub repo so it's always used over the system one by the end-user.
=> fix: Ensure flathub repo is always installed

fetch-quadlets.sh, just/custom.just, usr/libexec/configure-terminal.sh, usr/libexec/enable-bluefin-cli.sh, usr/libexec/prompt-add-profile.sh, usr/libexec/prompt-create-profile.sh, usr/libexec/prompt-remove-profile.sh, usr/share/ublue-os/bluefin-cli/bluefin-cli.sh, usr/share/ublue-os/bluefin-cli/prompt-integration
chore: simplify `ujust bluefin-cli`
=> feat: prompt integration with quadlets

usr/bin/podman-host
This script should be set up in VSCode as `Docker Path` like this:
This wrapper will adjust the USER for Distrobox and Toolbx containers only
This wrapper will work both with host-installed VSCode and with Flatpak too
This will allow to use pet-containers more seamlessly with VSCode devcontainer extension
=> feat: add podman wrapper for vscode

usr/etc/dconf/db/local.d/01-ublue
ctrl-alt-t = host
ctrl-alt-u = ubuntu
ctrl-alt-f = fedora
ctrl-alt-enter = bluefin-cli
These depend on the toolboxes being setup ahead of time otherwise prompt will just open to the host so it'll be benign for users that haven't set them up. 
--new-window is NOT working for me but we can file that upstream.
=> feat: set terminal quick launch shortcuts

usr/bin/podman-host
This improvement will correctly trick vscode to use distrobox to enter a container with `manager=distrobox` label.
This also symlinks the `~/.vscode-server` to `/var/tmp/` so that each distrobox has it's own server instance, avoiding possible conflicts
Fix #883
=> feat: improve podman-host script for vscode integration

just/custom.just
Matching the removal in config. We'll reinvestigate readding devbox when nix doesn't break selinux.
=> fix: remove nix shortcuts

packages.json, usr/etc/profile.d/brew.sh
This PR adds `gcc` to the bluefin package list (to be inherited by -dx as well) and adds a script in /etc/profile.d/ to source the brew shellenv script only from interactive bash terminals.
It DOES NOT address zsh or fish. TODO
=> feat: bring back the brew

Containerfile, usr/lib/systemd/system/brew-install-workaround.service, usr/lib/systemd/system/ublue-system-networked-tasks.service, usr/lib/systemd/user/ublue-user-networked-tasks.service, usr/libexec/ublue-system-networked-tasks, usr/libexec/ublue-user-networked-tasks, usr/libexec/ublue-user-setup
Also renames the flatpak installer to instead be a "networked tasks manager", of which Brew joins the roster.
=> fix: Allow brew-install to escalate when needed, fixes permission issue.

usr/lib/tmpfiles.d/pmcd.conf
noticed pmcd log directory was missing and service was failed.  Here's a tmpfiles.d fix for it.
=> fix: add pmcd log directory with tmpfiles.d

dx/usr/etc/zsh/zshrc
=> feat: add zsh config file

just/custom.just
this should overwrite /etc/profile.d/brew.sh with the one in /usr/etc regardless of whether the brew install actually happens in the test above.
=> fix: replace profile brew.sh on just brew command

Containerfile, usr/etc/security/limits.d/30-brew-limits.conf
`brew install texlive` was still failing with:
`Error: Too many open files @ rb_sysopen`
This sets a functional limits.conf soft nofile limit of 4096, but also sets the same default in systemd/user.conf which is required for the ulimit value to be respected in terminals running under Wayland/Xorg.
Relates: #670
=> fix: correct ulimit nofile issue with brew

usr/etc/dconf/db/local.d/01-ublue
I am embarrassed that we didn't turn this off on day 1.
=> fix: turn off audible bell in the terminal

Containerfile
Recommendation comes from jstone so that fonts can work better in flatpaks. Doesn't hurt to add this now and we might be able to remove the special case ones earlier in this file but I'd like to see how this works first.
=> fix: force clean font cache

.github/workflows/build_iso.yml, Containerfile
This PR uses the upstream action rather than our isogenerator action. Flatpaks will come as a separate PR into testing once I have done more local testing.
=> chore(ci): switch to upstream action

usr/share/ublue-os/topgrade.toml
We don't want to touch user git directories. Also alphabetize the list for sanity.
=> fix: disable topgrade git extension

.github/workflows/build.yml
ASUS/Surface don't have F38 upstream.
=> chore: remove broken f38 builds for asus/surface

just/bluefin-apps.just
=> fix: remove gnome touch extensions

Containerfile, install-akmods.sh
For some reason, the v4l2loopback kmod is not building on the current surface kernel (6.8.1) (even though it IS building for main 6.8.1).
This blocks installation of the kmod in question, so at least images are built.
=> chore(ci): TEMPORARY hack to build surface again

.github/workflows/build.yml
Reverts ublue-os/bluefin#1041
Everything else has to land before F40
=> revert: "feat: Add Fedora 40 builds to Bluefin"

.github/workflows/build_iso.yml
There is an issue with R2 and Rclone for uploading individual files: https://forum.rclone.org/t/cannot-copy-file-to-cloudflare-r2/43702/5
What enabling this does for rclone: https://rclone.org/s3/#s3-no-check-bucket
Should have no negative impact as long as the bucket exists.
=> chore(ci): Fix Upload to R2

Containerfile
We should grab all the docker stuff from the repo to keep everything matched.
=> fix: source docker-compose from one place

Containerfile
Ptyxis now lives at staging in a new Fedora 40 compatible format.
=> fix: Use Ptyxis from the ublue-os/staging copr repo

just/bluefin-system.just
Change the working dir to `/tmp` for `stress-ng` in `ujust benchmark` to prevent read/write permission error as in https://github.com/ublue-os/bluefin/issues/1036
Note: setting `--temp-path` in `stress-ng` is not sufficient because `stress-ng` will continue to use the current directory for I/O tests.
=> fix: change working dir to `/tmp` for `stress-ng` in `ujust benchmark`

usr/etc/yafti.yml
=> feat: freshen up yafti

boot_menu.yml
Defines boot menu entries for aurora in boot_menu.yml
=> chore: Add aurora to boot menu

build_files/base/cleanup.sh
Removes NVIDIA dracut and modprobe configuration from non-NVIDIA images
=> chore(cleanup): Remove NVIDIA configuration from non-NVIDIA images

packages.json
Fedora 40 dropped openssl1.1, Remove devpod temporarily.
=> fix(40-dx): temporarily removed devpod from 40

.github/workflows/reusable-build-iso.yml
It occurred to me when running the workflow that echoing out the secrets to outputs could potentially expose the secrets as environment variables in the workflow. 
This is not preferred and to be safe, I would rather define individual steps in the workflow that passes the correct secrets based on the `inputs.brand_name`
We can go back to the previous method if we have proof that it doesn't but I would rather not take the risk at the moment.
=> chore(ci): Fix passing secrets as outputs

.github/workflows/build-38-bluefin.yml, .github/workflows/build-39-aurora.yml, .github/workflows/build-39-bluefin.yml, .github/workflows/build-40-aurora.yml, .github/workflows/build-40-bluefin.yml
We are building and pushing to GHCR when a PR is added to a merge queue (`merge_group`), and also after the PR has been successfully merged into main (`push`).
To me, this seems like we are running a build when we do not need to, and unnecessarily taking up GHA runners.
This PR removes the builds after a commit has been merged to `main` and `testing` since these are ran during merge queue.
=> fix: remove duplicate builds on merge queue and push

system_files/silverblue/usr/etc/dconf/db/local.d/01-ublue
This `<Super>Space` keybinding should be used for the Search Light extension since it matches Alfred (MacOS).  
This PR is untested, and I will not be around to test it until tomorrow.
=> fix: change switch-input-source keybinding

system_files/silverblue/usr/etc/dconf/db/local.d/01-ublue
Reverts ublue-os/bluefin#1146
A clean install looks like normal GNOME.  Think I broke all dconf settings with this change.
=> Revert "fix: change switch-input-source keybinding"

build_files/dx/build-dx.sh
I feel this file should be sourced (and therefore executed) from the build-dx.sh file.  This is why we have no Podman or Docker sockets enabled in DX.
=> fix: source systemd-dx.sh from build-dx.sh script

system_files/silverblue/usr/etc/dconf/db/local.d/01-ublue
This keybinding should be reserved for Search Light, so we need to unset the existing default usage of the keybind.
This is the second attempt at this, since the first attempt broke all dconf settings - restoring the system to a near stock GNOME shell.
=> fix: remove switch-input-source keybinding

build_files/base/install-akmods.sh
=> fix: restore v4l2loopback module

just/bluefin-tools.just
From a fresh install with NVIDIA the systemd user service fails to start due to the `$HOME/.ollama/` dir not being present. Error message below:
```bash
Apr 19 13:48:46 desktop systemd[6775]: Starting ollama.service - The Ollama container...
░░ Subject: A start job for unit UNIT has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has begun execution.
░░ 
░░ The job identifier is 2686.
Apr 19 13:48:46 desktop ollama[57764]: Error: statfs /var/home/storopoli/.ollama: no such file or directory
Apr 19 13:48:46 desktop podman[57764]: 2024-04-19 13:48:46.644839296 -0300 -03 m=+0.017979759 image pull 6ffa7903c2d4b1a8c90be45edf1c3931>
Apr 19 13:48:46 desktop systemd[6775]: ollama.service: Main process …
```
=> fix: ujust ollama

build_files/base/aurora-changes.sh
This PR removes the line that deletes the .desktop file from the image to leave users the choice of a terminal. Ptyxis is still the default, but users who prefer a more native-feeling KDE terminal experience, Konsole should be available to launch and choose.
=> chore(aurora): remove the line that deletes the konsole desktop file

build_files/base/aurora-changes.sh, system_files/kinoite/usr/etc/profile.d/ksshaskpass.sh
Remove gnome-ssh-askpass configuration on Aurora
=> fix(Aurora): Configure ksshaskpass in /etc/profile.d

.github/workflows/build-38-bluefin.yml, .github/workflows/build-39-aurora.yml, .github/workflows/build-39-bluefin.yml, .github/workflows/build-40-aurora.yml, .github/workflows/build-40-bluefin.yml, .github/workflows/reusable-image-scan.yml
Enables SBOM and scanning for Aurora.
Adds a timeout to the SBOM actions.
Do not run SBOM generation in merge_group.
=> chore(ci): scanning fixes and enable aurora

.github/workflows/reusable-image-scan.yml
I was just having an issue with the image scan part of the github build actions. I was able to pinpoint the issue down to my github username having capital letters based on this error. 
```
- unable to parse registry reference="ghcr.io/APoorDev/aurora-asus@sha256:707967fb1d91da42774b8756c50c9df974919d1a84dd879ba7063c08aae99328": could not parse reference: ghcr.io/APoorDev/aurora-asus@sha256:707967fb1d91da42774b8756c50c9df974919d1a84dd879ba7063c08aae99328
```
I just stole the fix you all use in the reusable-build.yml and it was able to fix this error. Let me know if there is anything you would like changed or if I did something wrong!
P.S. 
Awesome project, Ive been having a lot of fun messing with and learning github actions!
=> fix(ci): Update reusable-image-scan.yml to use lowercase registry name

packages.json
Blur my shell previously couldn't be installed on a machine with GNOME >45, but it seems Fedora have bumped the versions in their repos.
It now can be installed on F40.
=> fix(bluefin): add blur-my-shell to Fedora 40

.github/workflows/build-bluefin-gts-iso.yml, .github/workflows/build-bluefin-latest-iso.yml
We don't have a manual workflow for building latest ISOs. We will need this in order to push up newer versions of latest ISOs.
=> fix(ci): Add ISO workflow for Bluefin for building latest

system_files/kinoite/usr/etc/profile.d/ksshaskpass.sh
#1208
SSH_ASKPASS should only be prompted when the user does not have a terminal. Otherwise, if /usr/bin/ksshaskpass isn't available it won't fall back to the terminal for input. To trigger ksshaskpass from the cmdline, use `ssh-add < /dev/null`
=> fix: Do not set SSH_ASKPASS_REQUIRE in Aurora

system_files/kinoite/usr/share/kde-settings/kde-profile/default/xdg/kwinrc
The default values for the wobbly windows desktop effect are kind of annoying. This changes this to more reasonable values.
=> fix(Aurora): Change the default values for the wobbly windows desktop effect

just/bluefin-system.just
This change allows the `ptyxis-transparency` recipe to set Ptyxis' opacity to values in the range (0-1]. The current recipe doesn't allow the user to spacify 1.0 as an opacity value, so transparency can't be completely turned off
=> feat: Allow just to turn off transparency for terminals

system_files/silverblue/usr/etc/profile.d/bluefin-fastfetch.sh
Using find on a directory returns the directory as well as contents. Don't do that.
=> fix: fastfetch don't include directory as option

system_files/silverblue/usr/etc/dconf/db/local.d/01-ublue
I found the default search light a little hard to read in some scenarios, so this PR darkens the background, rounds the edges to look more gnome-like and adds a very thin border.
Unfortunately blur was moved to the testing package since it caused a few bugs, so we are unable to use that.  
Updates Search Light's default appearance from:
To:
=> fix: update search-light default appearance

just/bluefin-system.just, system_files/shared/usr/libexec/configure-grub.sh
based on [bazzite configure grub just command](https://github.com/ublue-os/bazzite/blob/main/system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just#L44) with command from [hidden grub changeset](https://fedoraproject.org/wiki/Changes/HiddenGrubMenu)
=> feat: add configure-grub just command

aurora_flatpaks/flatpaks, bluefin_flatpaks/flatpaks
Add missing deja dup flatpak. Additionally add PikaBackup for Borg backup
=> fix: add missing backup flatpaks dejadup and pika

packages.json
I'm unsure why we removed xwaylandvideobridge from Bluefin.
=> feat: Add back xwayland video bridge to all images

just/bluefin-system.just
This is to test using bootc upgrade in lieu of rpm-ostree
=> feat(just): add update-ng shortcut

just/bluefin-tools.just
This changes Ollama's startup to require a user to run `systemctl --user start ollama`, rather than automatically starting on boot.
=> fix(dx): do not start ollama automatically

system_files/shared/usr/libexec/ublue-user-setup
power-profile-switcher is a good extension to install, but it's not a great default to start with; see the attached issue.
Remove enabling the switcher during user setup.
Fixes #1276
=> feat(framework): Stop enabling power-profile-switcher in ublue-user-setup

just/bluefin-system.just, packages.json, system_files/shared/usr/libexec/ublue-user-setup, system_files/silverblue/usr/etc/dconf/db/local.d/01-ublue
Adds `ujust configure-auto-power-profile <option>` command
Switches to new version of power profile switcher modified with notifications when the profile is changed.
=> feat: Restore power profile switcher on framework

.vscode/tasks.json, Justfile, scripts/build-image.sh, scripts/build-iso-ghcr.sh, scripts/build-iso-installer-main.sh, scripts/build-iso.sh, scripts/cleanup-dir.sh, scripts/cleanup-images.sh, scripts/common-build-iso.sh, scripts/get-defaults.sh, scripts/list-images.sh, scripts/run-booted-guest.sh, scripts/run-booted-home.sh, scripts/run-image.sh, scripts/run-iso.sh, scripts/sudoif.sh
=> feat(dev): improve just commands

system_files/shared/usr/lib/systemd/system/brew-upgrade.service, system_files/shared/usr/lib/systemd/system/brew-upgrade.timer
Currently, the updates of brew itself and brew packages are triggered at the same time. This can lead to the following error: 
```shell
Error:
Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
```
This fixes this issue by delaying the upgrade of brew packages by one minute and adding After=brew-update.service to brew-upgrade.service
=> fix: update brew packages only after brew itself is fully updated

just/bluefin-tools.just
The service name in the volume dependency was invoke-ai, when it should have been invokeai...
=> fix: correct invokeai volume service name

.github/workflows/build-39-bluefin.yml, .github/workflows/build-40-aurora.yml, .github/workflows/build-40-bluefin.yml
This restores building after new things land in the `main` branch. Skipping `testing` (just run those by hand) and also skipping Aurora 39
=> chore(ci): build on pushing to main

just/bluefin-apps.just
`bluefin-cli` will do this by default, but not implemented yet so I'm just staging this here for now.
=> fix(just): remove fleekbrew alias

system_files/silverblue/usr/etc/dconf/db/local.d/02-bluefin-folders
Corrects issue in app-folders dconf entry
=> chore: Use Containers folder by default

packages.json
This adds `android-tools` to dx images, a <2MB rpm with no dependencies. 
Simply installing adbe from brew is insufficient, adb itself from the system is required to be available. This package provides that for developers ootb.
=> feat: add android-tools to dx images

.github/workflows/build-39-aurora.yml, .github/workflows/build-39-bluefin.yml, .github/workflows/build-40-aurora.yml, .github/workflows/build-40-bluefin.yml
These workflows sounded good in theory, but in reality they are too flakey and take far longer than I would have hoped to complete.  
I feel they are getting in the way more than they are helping.  Maybe later I will make them a workflow we trigger on an individual image manually (maybe put in ublue-os/main), but running every build doesn't seem useful.
=> chore(ci): remove SBOM and scanning workflows

system_files/silverblue/usr/etc/dconf/db/local.d/01-ublue
Fixes the issue with overlapping running indicators and icons.
This setting changes the dock from having a single dot when many apps are open to displaying a dot for each open instance of the app.
Issue:
Workaround:
=> fix: change dash-to-dock running indicator to DOTS

packages.json
This PR adds the scanning apps skanpage for Aurora and simple-scan for Bluefin. Reason for layering directly is so the apps can access the drivers that are installed on the host system.
=> feat: add skanpage and simple-scan

system_files/silverblue/usr/share/ublue-os/motd/bluefin.md
We have https://feedback.projectbluefin.io set up to accept anonymous feedback via a form, this adds a link to the MOTD.
=> feat(motd): add link to feedback survey

packages.json
flatpak-builder can't easily be used in distrobox, and makes sense to have available in the developer version of a Flatpak-centric distro
=> feat: install flatpak-builder in dx

packages.json
KRFB isn't entirely reliable, and most people that would want to use a remote desktop would more than likely be better off using something like Sunshine
=> chore(aurora): Remove KRFB

just/bluefin-apps.just
This will allow users to have graph in Cockpit metrics and history.
pmlogger service won't run without the appropriate dirs and permission, too.
=> fix (ujust setup-cockpit): Fix PCP pmlogger permission and directories

just/bluefin-tools.just
Enabling volume will save user progress and account, so they wouldn't need to sign up over and over again after starting ollama-web systemd.
Also give user additional information regarding accessing Ollama Web UI.
=> feat(just): enable volume and add access info for ollama-web

just/bluefin-tools.just
Changes the InvokeAI port to use 9091 on the host since Cockpit Web Server also uses 9090.
This will not update existing systemd units, but maybe in future we can introduce a `--force` flag to overwrite existing units
=> fix: port clash between InvokeAI and Cockpit

.github/workflows/reusable-build.yml
Secrets can't be used out of org causing PRs to fail
=> fix(ci): Don't sign kernel on PR

.github/workflows/build-coreos-bluefin.yml
Workflow needs to be defined in main before it can run on testing branch.
=> chore(ci): Enable a CoreOS Kernel Workflow

packages.json
With ydotool, users can script and automate inputs for mouse and keyboard in a way that works on Wayland.
https://github.com/ReimuNotMoe/ydotool
=> feat: Add ydotool to the dx image

.github/workflows/reusable-build.yml
asus-linux only supports latest anyway, we've been pointing people off of these, we just never shut them off.
=> chore(ci): disable asus gts builds

.github/workflows/build-coreos-aurora.yml, .github/workflows/build-coreos-bluefin.yml
Build on every Tuesday via the cron. Note that the end devices will still check every day, so when we're pushing out new builds users will still get those fresh.
=> chore(ci): build stable tag weekly on tuesdays

.github/workflows/build-39-aurora.yml, .github/workflows/build-39-bluefin.yml, .github/workflows/build-40-aurora.yml, .github/workflows/build-40-bluefin.yml, .github/workflows/build-aurora-iso.yml, .github/workflows/build-bluefin-gts-iso.yml, .github/workflows/build-bluefin-latest-iso.yml, .github/workflows/build-coreos-aurora.yml, .github/workflows/build-coreos-bluefin.yml, .github/workflows/reusable-build-iso.yml, .github/workflows/reusable-build.yml, .github/workflows/reusable-image-scan.yml
=> chore(ci): clean up workflow names

system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-autumn-dynamic.xml, system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-spring-dynamic.xml, system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-summer-dynamic.xml, system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-winter-dynamic.xml
This PR changes the time at which the sun rises and sets in the seasonal Bluefin backgrounds to more closely match the variation in sunrise/sunset timing seen in real life. Daytime has a longer duration during summer and a shorter duration during winter.
Because the timing of sunsets and sunrises is dependent upon various factors, such as latitude and the specific date, choosing the exact time for the sunset and sunrise to begin for each background required some consideration.
Bluefin's seasonal backgrounds are inspired by the appearance of seasons in temperate, mid-latitude regions; for that reason, I chose to use the timings commonly experienced in mid-latitudes of around 40 - 45°. I averaged out the sunrise/sunset timing for each season to work around the variation within seasons. And …
=> feat: seasonal variation in sunrise/sunset times for seasonal Bluefin backgrounds

Containerfile
Standardized the [FromAsCasing](https://docs.docker.com/reference/build-checks/from-as-casing/) to match style recommendations and satisfy a build check. This will remove the build check's warning from the build process log.
=> style: Standardize FromAsCasing in dockerfile

build_files/base/copr-repos.sh
This COPR went away, everything is in ublue-staging now
=> fix: update gnome-vrr copr

system_files/silverblue/usr/etc/dconf/db/local.d/01-ublue
Let's free this back up, the bluefin-cli experience via brew is better.
=> feat: remove bluefin-cli shortcut

.github/workflows/reusable-build.yml, Containerfile, build_files/base/install-akmods.sh, build_files/dx/install-akmods-dx.sh, scripts/build-image.sh
This should install ZFS from the new `akmods-zfs` image (rather than akmods common image) and do so without a wasted copy layer.
Blocked by: https://github.com/ublue-os/akmods/pull/217
=> refactor: use akmods-zfs for ZFS install

.devcontainer/devcontainer.json
skopeo is a dependency used in the build scripts, but it's missing from the devcontainer environment. This fixes that.
=> fix: add skopeo to devcontainer's features

build_files/base/copr-repos.sh, packages.json
ptyxis is in F40 now, this switches the F40 build to just grab it from Fedora. We still build a one off for F39, when that moves out of support we'll completely be on distro ptyxis. 😄 🎊
=> feat: switch to distro ptyxis for F40

just/bluefin-system.just
This will remind users to add themselves to the right groups when they turn on devmode. 
Fixes #1501
=> fix(just): remind user to run dx-group

.github/pull_request_template.md, packages.json
chore: packages.json: Remove kdeplasma-addons (already included)
This package has been included for a long time in Kinoite and is
unlikely to go away so there is no particular need to list it here.
Fixes: https://github.com/ublue-os/bluefin/pull/1135
---
chore: Fix link to contributor's guide in PR template
=> chore: packages.json: Remove kdeplasma-addons (already included)

just/bluefin-system.just
Since this will eventually do a bootc switch and all the verbs upstream are switch I'm adding this as an alias for the rebase-helper. 
"channels" for gts, stable, etc make sense as a word so aligning all this up.
=> feat(just): add switch-channel shortcut

.github/workflows/reusable-build.yml, Containerfile
We have been experiencing multiple freezes with the newly released Nvidia 560 drivers, so we will pin to 555 while we investigate.
=> fix(nvidia): pin Nvidia drivers to 555

system_files/kinoite/usr/share/kde-settings/kde-profile/default/xdg/kwinrulesrc
this pr will add default kwin rules for google chrome stable/unstable 
it will fix this issue [default wayland icons for google chrome](https://www.reddit.com/r/kde/comments/tzw738/fix_generic_wayland_icon_in_task_manager_for/) 
also fix icon issue for steam flathub on KDE
=> feat: add kwin rules for google chrome stable/unstable and flathub steam

.github/workflows/reusable-build.yml, Containerfile
=> Revert "fix(nvidia): pin Nvidia drivers to 555"

.github/renovate.json5
The build-container-installer Docker images are not tagged with the commit sha (working on it).
For now, we can only use the tag names.
=> chore(ci): prevent pinning build-container-installer action digest

just/bluefin-tools.just
this is a first step on adding some actions to the ujust for ollama before potentially standardising this in bazzite too with another PR to bring "bazzite-tools.just" over. I've been using this, but i've seen others with the same opinion as me that i'd like to be able to mostly atomically clean up after it, as bazzite machines are often everything devices (so people are picky about things using their resources) I also can imagine a situation where in bazzite, people will want to tinker with this, but then remove and clear up afterwards because of the nature of the machine, and the users themselves are likely not as tech savvy as say aurora or bluefin people.
The script is a frankenstein now, but works in my test environment, backwards and forwards as necessary. I'm not sure what the …
=> feat: ollama ujust script, some additions for removal verbs for the ollama and open-webui containers.

system_files/silverblue/etc/dconf/db/local.d/01-ublue
This will supress the application crash dialog to a more reasonable time (20s instead of 5s)
=> feat(gnome): increase check-alive-timeout

just/bluefin-system.just
This commit adds logic to detect if the command is being executed on bluefin or aurora via /usr/lib/os-release. If it is executed on aurora it will leave out the calls to gnome-extensions as this is not available on aurora images.
=> fix: fix toggle-tailscale just command on aurora

just/bluefin-tools.just
The ollama-web container now does not require auth to be used.  This change disables authentication in the Ollama Web container.
This is safe because the configuration does not expose the web server to other machines on the network
=> feat: disable ollama-web quadlet auth

system_files/shared/usr/libexec/ublue-motd
reason this is needed is becuase while yes standard width is 80 as its set in default config it doesnt take into account what appers to be 2 character indent it has at which point it breaks anything thats 80 characters in size like the table it renders
=> fix: limited linesize to 78 characters to accomodate 80x24 terminal 

packages.json
Add git-credential-libsecret to allow storing git credentials in GNOME Keyring or KDE Wallet.
=> feat: add git-credential-libsecret to DX

system_files/kinoite/usr/share/kde-settings/kde-profile/default/xdg/kcm-about-distrorc
Resolves #1653 
The current link is invalid, since it is missing the colon in the protocol name.
=> fix(aurora): update KDE settings homepage link

just/bluefin-tools.just
Running daemon-reload is sufficient. Confirmed both ollama and ollama-web services load afterwards
=> fix(bluefin-tools): Don't explicitly start ollama after creating service

just/bluefin-system.just
We should have removed this a long time ago: 
Supported instructions: https://docs.projectbluefin.io/administration#changing-the-default-terminal-shell
=> fix(just): remove configure-shell

packages.json
This adds support for scx-scheds, same package in bazzite. This will only work on fsync kernels like the one in `:latest`. 
Running the tools on stock kernels is a noop so `:stable` and `:gts` are safe:
```
❯ sudo scx_bpfland 
[sudo] password for jorge: 
23:30:09 [INFO] scx_bpfland 1.0.4 x86_64-unknown-linux-gnu SMT on
Error: sched_ext_ops.dump() missing, kernel too old?
```
=> feat: add scx-scheds

packages.json
=> fix: remove nonexistant libsssd_sudo package

system_files/dx/usr/libexec/bluefin-incus
This change enables the incus-startup service which will start containers that were running at system shutdown, and start containers marked to start at boot.
It was overlooked previously.
=> fix: enable incus-startup service

system_files/shared/usr/libexec/check-sb-key.sh, system_files/shared/usr/libexec/ublue-motd
- remove warning prefix from message file
- add warning prefix to motd script
this change is a small fix to remove the redundant "WARNING" prefix for the GUI notification that bothered me
=> fix: update warning formatting

.github/workflows/build-latest-aurora.yml, .github/workflows/build-latest-bluefin.yml
The latest builds are currently failing while we're implementing the rechunk action.
This PR disables rechunks in latest (since they aren't working) to get the updates flowing again.
=> chore(ci): temporarily disable rechunk in latest

system_files/silverblue/etc/dconf/db/local.d/02-bluefin-folders
Part of #1711 
Moves applications into folders.  
Moves the Pika Backup & Media Writer icons to the Utilities folder
Introduces a Development folder
Renames Containers to Virtualization and adds virt-manager
Introduces a Productivity folder
=> chore(bluefin): update GNOME application groups

system_files/shared/usr/share/applications/Discourse.desktop
This is a more obvious label for the forum.
=> fix: rename discourse shortcut to community

build_files/packages-dx.sh, build_files/packages.sh
=> fix: ensure gnome-extensions-app is removed

system_files/silverblue/etc/dconf/db/local.d/01-ublue
Fixes #1707
Ctrl+alt+Return makes a lot of sense for this shortcut. Also re-ordered to have both Ptyxis keybinds side by side
On a side note: Might want to look into a better way of doing this. Seems a bit odd to include them one by one? Just a note for now.
```
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/']
```
Love the distro :) Keep up the great work ❤️ …
=> chore: added ctrl+alt+return keybind for host ptyxis

.github/workflows/reusable-build-iso.yml, dx_flatpaks/flatpaks
Podman Desktop is an example app that we would want to add specifically only to DX images. We can add others over time
=> feat: add specific flatpaks to dx images

packages.json
People who have OVFs, etc. and other VM formats have no way to convert those to KVM-usable images, so adding this.
https://github.com/libguestfs/virt-v2v
=> feat(dx): add virt-v2v

packages.json
Vanilla kernel doesn't support this, we'll get it in 6.12.
Part of #1717
=> fix: remove scx-scheds

just/bluefin-tools.just
=> fix: Ollama WebUI isn't started by the ujust command

build_files/copr-repos-dx.sh, build_files/install-akmods.sh
Now that main and hwe images are only providing negativo17, not rpmfusion, the 2 rpmfusion dependent akmods need some extra support, but other areas using rpmfusion can be cleaned up.
=> chore: update to handle the negativo17-only main image

.github/workflows/reusable-build.yml, build_files/cache_kernel.sh
PR #1722 passed all build checks, but after merging, we saw that for latest, where we use the stock upstream kernel, but with our added signature, rechunker complains of multiple kernels in /usr/lib/modules
Also, the method which was being used to remove the old kernel packages does not run when building locally on a Fedora host. So trying a different approach.
See: https://github.com/ublue-os/bluefin/actions/runs/11205608165/job/31145333321#step:23:233
=> chore: attempt to fix rechunker complaint of multiple kernels

.github/workflows/reusable-build.yml
GHCR push operations are subject to semi-frequent random failures. This will use the retry action to mitigate that issue.
=> chore(ci): retry on ghcr push failures

.github/workflows/reusable-build.yml, build_files/cache_kernel.sh, build_files/install-akmods.sh
This simplifies the logic around installing cached kernels by always doing it. This means that "vanilla"/"main" images will have the true vanilla kernel replaced by essentially the same package, but the repackaged version which we have signed in addition to the Fedora signature.
This fixes a bug introduced in #1722 where accidentally stopped installing the cached kernels for asus/surface images.
=> chore(ci): always replace kernel packages

build_files/cache_kernel.sh
Fixes bug in #1752 which ignored the fact that asus/surface images in Bluefin are sourced from the HWE images, thus they already have their expected kernels.
I do think this end state is a bit nicer though as it is easier to grok that this script only works on specific akmods flavors rather than the nvidia_type which didn't seem to have a clear correlation to replacing the kernel.
I apologize for the noise and confusion on this topic tonight.
=> chore(ci): replace vanilla kernels not asus/surface

.github/workflows/reusable-build.yml
Use the same conditionals as on build image step to avoid wasting time freeing space we aren't going to use if not executing the build.
Also moved maximize space step to just before we start using the disk for significant tasks (eg, pulling podman images and building).
=> chore(ci): only maximize space if building image

README.md
The removed line was in reference to the hyphen in ublue-os. It's not relevant anymore with the new MOK password, so it can be swept right on out.
=> docs: remove out-of-date line in readme

packages.json
This commit makes [io.github.mpobaschnig.Vaults](https://flathub.org/apps/io.github.mpobaschnig.Vaults) functional. Although cryfs can be installed by the user through brew or a distrobox, Vaults won't detect it. It must be installed directly onto the system to be detected by Vaults. Of the four months I've used Bluefin, this is the only package I've been stuck with layering.
Why provide support for Vaults? KDE Plasma contains a built-in feature called vaults that allows for the creation of locally encrypted containers. This can offer a second layer of encryption beyond LUKS or allow you to create encrypted containers on an otherwise unencrypted file system. This feature was added in Plasma 5.11.
Vaults provides support for that feature on Gnome, helping bring feature parity between the …
=> feat: add cryfs to bluefin

.github/workflows/build-latest-aurora.yml, .github/workflows/build-latest-bluefin.yml
Related to changes made in bluefin repo merge rulesets, we need to always run the "latest" build workflows for both aurora and bluefin to ensure that merge checks pass both for the pre-merge checks and the merge queue checks.
=> chore(ci): always build latest images for both varieties

just/bluefin-system.just, system_files/dx/usr/libexec/bluefin-dx-groups
just dx-group would not add group to user. with this pr it checks if the group exists in `/etc/group`, and if not it appends from /usr/lib/group
=> fix: just dx-group append group entry from /usr/lib/group

.github/workflows/build-coreos-aurora.yml, .github/workflows/build-coreos-bluefin.yml, .github/workflows/reusable-build.yml
I really liked the idea of having a daily build of the stable channel as of talked in https://github.com/ublue-os/bluefin/issues/1736. So I tried my best to implement this feature.
Changes made:
- Aurora & Bluefin stable workflow now scheduled to build everyday and let you specify a "weekly_tag_day".
- If the workflow is not run via schedule, tag with stable and stable-daily.
- If the workflow is run via schedule and matches the weekly_tag_day, tag with stable and stable-daily.
- If the workflow is run via schedule but not matches the weekly_tag_day, tag with stable-daily.
Hope this is the correct implementation, thanks for this awesome project.
=> feat: enable stable-daily channel

packages.json
This PR adds borgbackup to the image to address this issue: https://github.com/ublue-os/bluefin/issues/1778
Forum Thread: https://universal-blue.discourse.group/t/borgbackup-via-homebrew-not-working-great/4495
=> feat: Add Borgbackup on the image for both Aurora and Bluefin

system_files/shared/usr/bin/ublue-rollback-helper
Adding stable-daily to the rebase helper options for https://github.com/ublue-os/bluefin/issues/1782
Possibly should update the message as well. Open to suggestions here. Below is one option although seems a little verbose.
`The default selection is gts, stable (weekly builds) and stable-daily (daily builds) are for enthusiasts, and latest is for testers`
Example from running it locally (rebasing from stable -> stable-daily)
```
./ublue-rollback-helper 
Choose your action.
Which Tag would you like to rebase to?
The default selection is gts, stable is for enthusiasts, and latest is for testers
Rebase Target is ghcr.io/ublue-os/bluefin-dx:stable-daily
Confirm Rebase
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:stable-daily
Importing: …
```
=> feat: ublue-rollback-helper - add stable-daily to targets

packages.json
This commit adds the fmt package to bluefin-gts which was mysteriously absent.
Resolves https://github.com/ublue-os/bluefin/issues/1798.
=> fix: fix cryfs error on bluefin-gts

.github/workflows/build-coreos-aurora.yml, .github/workflows/build-coreos-bluefin.yml
This puts the weeklies the same as GTS, sunday nights. Also added an extra 4m to the cron so that the gts builds populate the build queue first.
=> feat(ci): Build stable weekly on the same day as gts

.github/workflows/build-coreos-aurora-daily.yml, .github/workflows/build-coreos-aurora-weekly.yml, .github/workflows/build-coreos-bluefin-daily.yml, .github/workflows/build-coreos-bluefin-weekly.yml, .github/workflows/reusable-build.yml
I have refactored the stable-daily tagging logic to make it much more readable. I hope M2 is happier with this code.
Reference: https://github.com/ublue-os/bluefin/issues/1804
Psuedo logic:
```
if triggered by schedule and its not weekly_tag_day; then
tag with stable-daily
else
tag with stable stable-daily
fi
```
In the code, I used the explicit term `stable` instead of `${FEDORA_VERSION}` to improve readability. I chose this because we are already in stable logic, so this would always be `stable`. If you prefer `${FEDORA_VERSION}` I can, of course, put that back in.
Manual triggered run will produce: stable, stable-daily
Schedule triggered run on weekly_tag_day: stable, stable-daily
Schedule triggered run on non weekly_tag_days: stable-daily
On top of this I made changes that will allow …
=> refactor(ci): stable-daily tagging

system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Upstream issue proposing this (years ago) is found here: https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/issues/24
Justification to not set the shortcut by default by GNOME dev (Ubuntu has that default) is:
> The original purpose of that shortcut was to provide quick access to desktop icons (in fact, the internal shortcut name is show-desktop). As we no longer have those, the shortcut is no longer useful to most users.
Main counter-argument is: Being able to hide all windows (and showing one of Bluefin's beautiful wallpapers 🦕 or whatever) *is* already a use case.
GNOME dev counters that with
> Sure, and nobody is planning to remove the shortcut. But it's not a strong argument for a default shortcut, given that someone who installs and configures conky can also assign a …
=> feat: hide all windows (show desktop) via Super+D

system_files/shared/usr/bin/ublue-rollback-helper
This PR introduces a limitation on the date selection in `ublue-rollback-helper`, restricting the available options to the last 31 days.
As outlined in issue https://github.com/ublue-os/bluefin/issues/1821, the current implementation allows users to select from all available dates, which currently totals around 176 options. This extensive list will 'overflow' and results in showing only old dates to the user. 
By limiting the date range to the last 31 days, we can prevent this overflow issue, ensuring that users have a manageable selection that is sufficient for pinpointing specific issues via the date picker.
<details>
<summary>Current behavior</summary>
```
Which Tag would you like to rebase to?
The default selection is gts, stable (weekly builds) and stable-daily (daily builds) are for …
```
=> fix: limit the number of days in rollback-helper

system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Seems to be working in bazzite so let's just match their setting:
Attempts to fix #1843
=> fix: match bazzite's vrr/fractional scaling options

build_files/bluefin-changes.sh
This PR tries to fix https://github.com/ublue-os/bluefin/issues/1843
Enabled `glib-combile-schemas --strict` again and strips out incompatible schema values (pre F41) via dirty sed:
`, 'xwayland-native-scaling'` and `accent-color="slate"`
Probably there are nicer ways to do this, but it results in strict checked schemas as tested on latest, gts and beta:
```
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-unverified-registry:ghcr.io/befanyt/bluefin:gts
Digest: sha256:7b19b8a71a101a9e405b4605e0750aff4e2b2d234f3c4a46f722fdcaa3174a30
Version: 39.20241027.0 (2024-10-28T20:46:13Z)
❯ gsettings get org.gnome.mutter experimental-features
['scale-monitor-framebuffer']
❯ rpm-ostree status
State: idle
AutomaticUpdates: …
```
=> fix: broken scale-monitor-framebuffer

packages.json
This just adds `podman-machine` support for Bluefin. This fixes #1825
=> feat: make podman-machine work by default OOB

.github/workflows/build-image-latest.yml
it says Stable ISOs in Github UI but it's actually latest.
A little something I missed in my review.
=> chore: fix name of Latest ISO workflow

Justfile
The option is WEB_UI. This was not caught because it already defaults to false. This should now actually take the option you place in there.
=> fix: WEBUI to WEB_UI

system_files/shared/usr/share/ublue-os/topgrade.toml
This is much more of a RFC than anything concrete, I just wanted to really know what you guys feel like should be directly supported by bluefin (and thus should be added to this `only` array). Restricting topgrade on ujust update should mitigate issues like #1912 and #1845
=> chore(just): restrict topgrade to only supported things

.github/workflows/build-image-beta.yml, .github/workflows/build-image-gts.yml, .github/workflows/build-image-latest.yml, .github/workflows/build-image-stable.yml, .github/workflows/reusable-build.yml
Fix a typo to match for stable weekly tag.
Today scheduled run where it missed the stable tag because of checking for "scheduled" instead of "schedule"
https://github.com/ublue-os/bluefin/actions/runs/11762641102/job/32765731717#step:14:26
Should fix https://github.com/ublue-os/bluefin/issues/1918
And you probably want a manual rebuild today of stable images, because it missed the scheduled one.
=> fix: stable tag on schedule

.github/changelogs.py, .github/workflows/build-image-stable.yml, .github/workflows/generate-release.yml, .github/workflows/reusable-build.yml, .gitignore, Justfile, build_files/base/03-install-kernel-akmods.sh
Improve Justfile Workflow
Support multiple dated tags per day
=> chore(ci): clean changelog/Workflow

.github/workflows/build-image-gts.yml, .github/workflows/build-image-stable.yml, .github/workflows/reusable-build.yml, Justfile
Configure a kernel-pin for stable and gts to avoid issues with tailscale.
=> feat: enable kernel_pin and pin kernel for stable/gts

.github/changelogs.py, .github/workflows/build-image-latest.yml, .github/workflows/reusable-build-iso.yml, Justfile
=> fix: CI fixes for ISO/Changelogs

packages.json
=> fix: deprecate playerctl

system_files/shared/usr/share/ublue-os/topgrade-bootc.toml
Should make it so when using LockLayering, the bootc topgrade file will also follow our allowlist from the other topgrade config, seems to work locally
=> chore(topgrade): make it so topgrade-bootc follows allowlist pattern

just/bluefin-apps.just, just/bluefin-system.just, just/bluefin-tools.just, system_files/dx/usr/libexec/bluefin-incus, system_files/shared/usr/share/ublue-os/just/10-update.just
=> chore(just): clean up ujust recipes to fit newer style

packages.json
We should also probably remove libratbagd from packages.json, apparently it got replaced entirely by Solaar AFAIK
=> chore(f39): remove vestigial f39 reference in packages.json

just/bluefin-apps.just, just/bluefin-system.just
Did an oopsie when was refactoring the ujust recipes, this should make -dx detection work fine on `ujust devmode` and `ujust incus`. Sorry guys
=> fix(ujust): dx detection on nvidia/surface/others

.github/workflows/clean.yml
This will clean up images older than 90 days, from bsherman. This has been running fine on kernel-cache.
Only adding a few images, we can add more over time.
=> chore(ci): add 90 day cleanup action

system_files/kinoite/usr/lib/tmpfiles.d/usr-share-ssdm-themes.conf
=> fix(sddm): Use default permissions for themes directories

just/bluefin-system.just
Apparently specifically the bash shell sets `$GROUPS` as an array for GIDs the current user is on. This should force it to use the declared array instead of the built-in. Fixes: #1972
(I also did not run into this issue during testing, super weird)
=> fix(ujust): dx-group using built in GROUPS array in bash

build_files/base/07-base-image-changes.sh, just/bluefin-system.just, system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Nvidia driver documentation specifies that the mutter experimental feature 'kms-modifiers' should be set when using the driver.
This condtionally sets this feature on Bvidia image builds.
Also, removes the ujust toggle-vrr recipe since if used it would lose this setting and vrr is now default on our images anyway.
Closes: #1567
=> feat: set mutter experimental kms-modifiers for nvidia

system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md
`ujust ollama` doesn't exist anymore, but I still got a tip to use it. This PR should fix that.
=> chore: remove 'ujust ollama' from motd tips

.github/changelogs.py
This PR adds the `nvidia-driver` version on top of the major packages list as requested in https://github.com/ublue-os/bluefin/issues/1981 and results in the following table:
| Name | Version |
| --- | --- |
| **Kernel** | 6.11.3-300 |
| **Gnome** | 47.1.1-1 |
| **KDE** | 6.2.3-1 |
| **Mesa** | 24.2.4-1 |
| **Podman** | 5.3.0-1 |
| **Nvidia** | 565.57.01-4 |
=> chore: show nvidia version in changelog

just/bluefin-apps.just
This should setup command-not-found alongside brew-setup. The only thing missing is fish support that I couldnt set up yet (idk why it isnt working). Otherwise this seems good? Just needs a bit more testing. - Fixes #1327
=> feat(just): add brew-command-not-found setup

.github/changelogs.py, .github/workflows/build-image-beta.yml, .github/workflows/build-image-latest.yml, .github/workflows/build-image-stable.yml, .github/workflows/build-iso-latest.yml, .github/workflows/generate-release.yml, .github/workflows/reusable-build-iso.yml
Removes a few footguns with our CI.
1. Disable building bluefin/aurora separate from each other to avoid a release saying an image exists.
2. Remove having to manually run generate-release to actually have latest get tagged in releases
3. Changelogs remove KDE in gts images and make sure tag exists in all images.
4. Build ISOs tries to not run as many images and use hwe images.
=> fix(ci): remove footguns.

packages.json
This was mentioned in a review and I had forgotten about this thing and we don't use it so removing it.
Also the newer versions of gnome-tour are much nicer than the old ones so restoring this, it's a one time thing for new users.
=> fix: remove background-logo extension, restore gnome-tour

packages.json
This should fix some weird font issues that I had discussed with @RoyalOughtness. 
For example, if you open up [this post](https://www.reddit.com/r/CrestedGecko/comments/1anzfkz/%E1%A5%B2_%E1%A5%A3%E1%A5%86%F0%9D%97%8D_%E1%A5%86%F0%9D%96%BF_%E1%A5%B1%E1%A5%86%E1%A5%A3%E1%A5%B1_%E1%A5%95%E1%A5%86%E1%A5%92%E1%83%AB%E1%A5%B1r_%E1%A5%95%D2%BB%E1%A5%A1_z%D1%96gg%E1%A5%A1_%D1%96s_s%E1%A5%86_%E1%A5%B4%E1%A5%B2%E1%A5%A3m_%E1%A5%B2%E1%A5%92%E1%83%AB/) on bluefin currently the weird font just breaks everything. This PR is meant to fix stuff like that, although maybe this might be an edge case that does not need to be addressed
=> feat(packages): add google-noto-fonts-all

system_files/kinoite/etc/profile.d/aurora-fastfetch.sh, system_files/kinoite/usr/share/fish/vendor_conf.d/aurora-fastfetch.fish, system_files/shared/usr/libexec/ublue-bling-fastfetch, system_files/shared/usr/libexec/ublue-motd, system_files/shared/usr/share/ublue-os/motd/themes/blue.json, system_files/shared/usr/share/ublue-os/motd/themes/green.json, system_files/shared/usr/share/ublue-os/motd/themes/orange.json, system_files/shared/usr/share/ublue-os/motd/themes/pink.json, system_files/shared/usr/share/ublue-os/motd/themes/purple.json, system_files/shared/usr/share/ublue-os/motd/themes/red.json, system_files/shared/usr/share/ublue-os/motd/themes/slate.json, system_files/shared/usr/share/ublue-os/motd/themes/teal.json, system_files/shared/usr/share/ublue-os/motd/themes/yellow.json, system_files/silverblue/etc/fish/conf.d/bluefin-fastfetch.fish, system_files/silverblue/etc/profile.d/bluefin-fastfetch.sh
This PR adds support for accent color theming on the MOTD and fastfetch for Aurora and Bluefin
MOTD:
[aurora-motd.webm](https://github.com/user-attachments/assets/df4fd87c-091a-452e-b762-e05be23f19f2)
[bluefin-motd.webm](https://github.com/user-attachments/assets/6bb0c818-12ed-4d60-b6f3-01184edf1919)
Fastfetch:
[aurora-neofetch.webm](https://github.com/user-attachments/assets/379028d1-103d-41e7-8be4-2e3eb9d6566f)
=> feat: accent color theming for fastfetch and MOTD

.github/workflows/reusable-build-iso.yml
Replaces `-hwe` with `-asus`/ `-surface` in each checksum file when copying/renaming built ISOs.
Related: #2003 , castrojo/bluefin-website#54
Test run of 'Latest ISO' workflow: https://github.com/joestrouth1/bluefin/actions/runs/12171389483/job/33948194059
=> fix: rename HWE ISOs in checksum files

system_files/shared/usr/share/ublue-os/motd/themes/blue.json, system_files/shared/usr/share/ublue-os/motd/themes/green.json, system_files/shared/usr/share/ublue-os/motd/themes/orange.json, system_files/shared/usr/share/ublue-os/motd/themes/pink.json, system_files/shared/usr/share/ublue-os/motd/themes/purple.json, system_files/shared/usr/share/ublue-os/motd/themes/red.json, system_files/shared/usr/share/ublue-os/motd/themes/slate.json, system_files/shared/usr/share/ublue-os/motd/themes/teal.json, system_files/shared/usr/share/ublue-os/motd/themes/yellow.json
This is kind of a workaround but it works perfectly well. It just makes it so light and dark themes look the same!!! LES GOOOO this should be the last fix for the MOTD
=> fix(motd): use bold for color blocks instead of background color

build_files/base/18-workarounds.sh
Fedora has rolled back the problematic issue:
https://bodhi.fedoraproject.org/updates/FEDORA-2024-dd2e9fb225  
Additionally I've left this one as a commented out example for future pins.
=> fix: remove pkcs11-provider workaround

system_files/shared/usr/bin/ublue-rollback-helper
Use the image registry that was used when building the currently running image, instead of unconditionally switching to `ghcr.io/ublue-os`.
See also #2016.
=> feat: allow non-official image repositories in ublue-rollback-helper

.github/workflows/reusable-build.yml
This restores the old behavior (pre-#1867) of storing the GitHub repository owner of the repository used to build the image in `image-info.json`, instead of always using `ublue-os`. This is relevant for people (like me) building their own forks of this repository.
Also, clean up unnecessary trailing whitespaces in the affected files as well.
=> fix: pass `repo_organization` to build script to ensure correct image metadata

just/bluefin-apps.just
This should fix #1995. Tracking the container existence makes it so the user can know if the webui is even up or not, the service itself doesn't seem to do much
I also removed the pmlogger thing because I dont know if it is necessary...? Cockpit seems to work fine without that, it didnt seem to work before anyways
=> feat(ujust): make setup-cockpit work more consistently and track container existence

system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
GNOME Settings only shows '\<Super\>Down' as the "unmaximize" keybinding however, '\<Alt\>F5' is also there as a hidden default.
This is confusing enough, but the real trouble is this keybinding conflicts with VSCode's default "next diff" shortcut.
As this hidden shortcut seems somewhat deprecated and conflicts with VSCode, which we ship in DX, I'm removing it.
=> fix: remove Alt-F5 from GNOME unmaximize keybinding

build_files/dx/09-cleanup-dx.sh
kvmfr and podman-bootc repos are currently not being disabled in the cleanup stage
=> fix(dx): disable kvmfr and podman-bootc repos on cleanup

Justfile
In at least some cases, it seems that podman leaves behind temporary files created during the `podman image scp` process.
Since this is used by both the rechunk and build-iso just recipes when using locally built images, this can result in a lot of disk space used when testing locally.
Creating a temporary directory, overriding TMPDIR when calling `podman image scp`, and then removing that temporary directory works around the issue.
=> chore: workaround podman image scp leaving behind temporary files in /var/tmp

just/bluefin-system.just
This should guarantee the tmp directory does not conflict with something else while also being writeable. Fixes: #2060
=> fix(ujust, benchmark): make benchmark be run on unique path on tmp

build_files/base/09-hwe-additions.sh
Support GPIO pins on the Surface Book 2, Surface Pro 9/10, and Surface Laptop 5/6
=> feat(hwe-additions): Load pinctrl for more Surface devices

system_files/shared/usr/share/ublue-os/bluefin-cli/bling.sh
This should just return early return if the script has already been sourced, this should be tested by someone else just to make sure!!!
=> fix: return on bling.sh if it already got sourced

build_files/shared/build-dx.sh
Remove -dx from the pretty name in OS release info to consolidate brew stats given it is a mode and not a variant
=> chore(build-dx): Clean up pretty name in OS release info

.github/workflows/build-image-gts.yml, .github/workflows/build-image-latest.yml, .github/workflows/build-image-stable.yml
=> chore(ci): Temporarily disable ISOs

system_files/silverblue/usr/share/ublue-os/motd/bluefin.md
bluefin-cli is opt-in - The way it reads now it implies that everyone is using it, this will make it clearer I think.
=> docs: update motd

.github/workflows/build-image-gts.yml, .github/workflows/build-image-stable.yml
Fixes #2103 - hopefully we can avoid this entirely.
=> fix: pin to 6..8.11 kernel

build_files/dx/09-cleanup-dx.sh
There are no units named `pmie.service` or `pmlogger.service`. Trying to disable them is throwing errors that these units do not exist when building dx variants.
Stable: https://github.com/ublue-os/bluefin/actions/runs/12604017907/job/35130160146
```
2025-01-03T21:38:43.1653202Z + systemctl disable pmie.service
2025-01-03T21:38:43.1774426Z Failed to disable unit: Unit pmie.service does not exist
2025-01-03T21:38:43.1775098Z Failed to disable unit: Unit pmie.service does not exist
2025-01-03T21:38:43.1783989Z + systemctl disable pmlogger.service
2025-01-03T21:38:43.1904775Z Failed to disable unit: Unit pmlogger.service does not exist
2025-01-03T21:38:43.1905417Z Failed to disable unit: Unit pmlogger.service does not exist
```
GTS: …
=> chore: remove systemd unit disable for unknown services on bluefin-dx

.github/workflows/generate-release.yml, .github/workflows/reusable-build-iso.yml, .github/workflows/reusable-build.yml, .github/workflows/shared/install-just.sh
I have noticed an increase in workflow failures due to flaky errors with installing `just`. For example, in the past few days, the following jobs to build images have failed:
- https://github.com/ublue-os/bluefin/actions/runs/12600726942/job/35120374239
- https://github.com/ublue-os/bluefin/actions/runs/12576191989/job/35052038346
- https://github.com/ublue-os/bluefin/actions/runs/12567338911/job/35033772133
The command `curl -L https://api.github.com/repos/casey/just/releases/latest | jq -r '.tag_name'` is sometimes returning "null" instead of an actual version, but it's difficult to tell if the curl call is failing or if it's returning a payload that is being parsed incorrectly.
In either case, adding `--retry` to curl and if it's still null, hardcoding a known good version should do …
=>  fix(actions): try to recover if just fails to install

packages.json
People without dx should be able to use this.
=> fix: move powertop to all images

build_files/base/18-workarounds.sh
Fixes #2118 
See also: https://universal-blue.discourse.group/t/bluefin-enterprise-woes/6157/4
=> fix(pin): sssd to 2.10

system_files/shared/usr/libexec/ublue-system-setup
See https://github.com/ublue-os/aurora/pull/106.
Two issues with the system setup script:
1. `$SYS_ID` is not defined anywhere, so we never actually take the branch to compare the product name.
2. I'm assuming `$SYS_ID` is supposed to be defined as the contents of `/sys/devices/virtual/dmi/id/product_name`, which is from Bazzite's [`/usr/libexec/hwsupport/sysid`](https://github.com/ublue-os/bazzite/blob/abeed9ace51ebb1297d975de4ceb72c41b4da363/system_files/desktop/shared/usr/libexec/hwsupport/sysid#L3). This string is something like `Laptop 13 (AMD Ryzen 7040Series)` which doesn't match the regex `Laptop (*`.
I discovered this when I noticed that I didn't have any of these tweaks on my Framework 13 (with Aurora). I checked the first log entry for `ublue-system-setup.service` and it …
=> fix: Framework 13 AMD support

just/bluefin-system.just
Closes #2121.
This recipe is pulled straight from Bazzite. In Bazzite, users first call Bazzite's setup-virtualization recipe, which sets up the `kvm.report_ignored_msr` karg. In Bluefin/Aurora, we have the `-dx` variant for virtualization which does not set this karg.
To fix the recipe, we just need to remove the guard for the `kvm.report_ignored_msr` karg and just append it to the end.
I confirmed that this works in a VM.
=> fix(just): fix configure-vfio recipe

.devcontainer/devcontainer.json, Justfile
Fixes https://github.com/ublue-os/bluefin/issues/2046
I've confirmed that the following recipes are working properly inside the devcontainer:
```
just build
just run
just build-iso
just run-iso
```
=> feat: add devcontainer

.github/workflows/build-image-gts.yml, .github/workflows/build-image-stable.yml
Otherwise people with IPU cameras get stuck, I'm going to push out new gts/stable since this one sucks. 
https://hansdegoede.dreamwidth.org/29039.html
=> pin: kernel back to 6.11.8

system_files/shared/usr/lib/systemd/system/ublue-system-setup.service, system_files/shared/usr/libexec/ublue-system-setup
Fixes: https://github.com/ublue-os/aurora/issues/124
=> fix: remove sudo from ublue-system-setup

Justfile
This category doesn't exist, we need to remove it or it fails to ingest in ah.
=> fix(artifacthub): remove artifacthub category

.github/workflows/build-image-gts.yml, .github/workflows/build-image-stable.yml, Justfile
Note: 6.12.9 is the current coreos-testing kernel and is known to have fixed the AMD suspend bug.
We're switching the "bluefin:stable" builds to use this kernel since it allows us to ship not-broken kernel and not-broken nvidia.
We don't have a pre-existing build for Fedora 40, so we can't ship a fix for "bluefin:gts" at this time.
Partial fix for #2157
This fixes `bluefin:stable`  but  not `bluefin:gts`
=> feat: update bluefin stable kernel pin to 6.12.9

system_files/shared/usr/share/polkit-1/rules.d/99-pcscd.rules
This is from the Yubikey guide
https://github.com/drduh/YubiKey-Guide/issues/376
It allows users in the wheel group to access gpg signing card
=> fix: allow wheel users to access yubikeys

build_files/base/05-override-install.sh, packages.json, system_files/shared/usr/share/ublue-os/topgrade.toml
=> fix: update topgrade.toml

system_files/shared/usr/share/ublue-os/just/10-update.just
Meant to mitigate the current things we are running into with topgrade. This should work just fine - tested it locally and it acts just fine
=> fix: make ujust update use direct calls to rpm-ostree and others

system_files/shared/usr/share/ublue-os/topgrade.toml
we downgraded to topgrade 15.0.0 which doesn't have support for bootc. This key cannot be handled and throws an error.
=> fix: remove bootc key from topgrade

system_files/shared/usr/share/ublue-os/just/10-update.just
This puts guards around flatpak updates (user and system) and brew.
=> chore: add guards to ujust update

system_files/dx/etc/skel/.config/Code/User/settings.json
Automated updates aren't useful since updates are handled through the image.  It just creates a pop-up that nobody can do anything with
=> chore: disable vscode automated updates

system_files/shared/usr/share/ublue-os/just/10-update.just
`ujust changelogs` now shows the release notes, taken from https://github.com/ublue-os/bazzite/pull/2137
`ujust changelogs-fedora` will pull the package release notes from fedora.
=> feat(just): add bluefin-specific changelogs

system_files/dx/etc/skel/.config/Code/User/settings.json
This PR implements the proposal written in https://github.com/ublue-os/bluefin/issues/2196
It fixes the nerd fonts in VS Code, see screenshot with the Bluefin header inside the terminal of VS Code.
I tried to follow all conventions. Since this is my first (small) contribution, let me know if I overlooked something.
=> feat: Add Nerd-Font Symbols to VSCode Editor Config #2196

system_files/shared/etc/geoclue/conf.d/99-beacondb.conf
Reverts ublue-os/bluefin#2204
This is in the RPM now, no need to have it per-image.
=> revert: "feat: Fix geolocation (Primarily for timezone detection) now that Mozilla has exited"

build_files/base/18-workarounds.sh, build_files/shared/build-base.sh, build_files/shared/build-dx.sh
`main` has removed the workaround since upstream should have fixed it.
Relates: ublue-os/main#721
=> chore: remove alternatives workaround

.github/workflows/build-image-latest-hwe.yml, .github/workflows/build-image-latest-main.yml, .github/workflows/build-images.yml
This pins bluefin latest kernels to our newest good builds:
- main/nvidia flavors: 6.12.15
- hwe/hwe-nvidia flavors: 6.12.12.bazzite
These are the newest known good kernels for the respective flavors.
The purpose of the pin is avoid shipping kernel 6.13 until the major issues are resolved (eg "bad page state" and fuse issues crashing systems and flatpaks).
=> chore: pin latest to last 6.12 kernel

Justfile
This is an adaptation of the same recipe used in Aurora that we use to retag broken NVIDIA images.
=> feat: add justfile recipe to retag broken NVIDIA ghcr images

.github/workflows/reusable-build.yml
Due to the retry action (which I'd like to remove sometime soon), we need to add some strange hackery to be able to fetch the outputs from the steps.
=> fix: reference digest from retry action correctly

build_files/base/05-override-install.sh, packages.json
This should pull in an old version of the bluefin wallpapers package, so we dont get the black screen issue since... we dont get the new wallpaper at all!
Fixes: #2242
=> fix: remove march wallpaper from GTS (f40)

build_files/shared/build-base.sh
reverts commit 398bc8607a1de08a40295ae0310c6f4f7357fa75
dnf5 got updated and fixes the gpg errors. Now builds are failing because of the downgrade
=> fix: revert dnf5 downgrade

Justfile, build_files/base/18-workarounds.sh
Also fixes a few issues with just run-iso command.
=> fix: Remove nonAscii file name for iso building

system_files/dx/usr/lib/systemd/user/bluefin-dx-user-vscode.service, system_files/shared/usr/lib/systemd/user/ublue-flatpak-manager.service, system_files/shared/usr/lib/systemd/user/ublue-user-setup.service
Porting changes from https://github.com/ublue-os/aurora/pull/206 to here.
I'm not sure if GDM has the same design as SDDM, which would be an issue for GDM. In any case, we are still running these user services for the root user.
=> fix: only run ublue user services for human users

build_files/dx/04-override-install-dx.sh, just/bluefin-system.just, system_files/dx/usr/lib/dracut/dracut.conf.d/80-vfio.conf, system_files/dx/usr/libexec/bluefin-dx-kvmfr-setup
This will be kept as a draft in-case more changes are needed, but from what i can tell, dracut is being run as part of the build process so the vfio modules should be included into initramfs with the image with this inclusion.
the just recipes and the script for kvmfr has been updated to reflect this
also minor changes to heredocs in some recipes to make the just highlighting work for me in vscode when writing this.
I will be making a similar PR to Aurora with the same updates later.
=> feat: Update VFIO to be bootc compliant

just/bluefin-apps.just, system_files/shared/usr/share/ublue-os/just/10-update.just
Fixes #2221 by picking the correct channel and by selecting the currently deployed version tag.
=> fix: ujust changelog shows stable channel even when on GTS

just/bluefin-apps.just
I noticed the lack of the `install-gaming-flatpaks` command for `ujust` when moving to Bluefin from Aurora, and wanted to make a PR to add it to Bluefin in hopes that it might be useful to other users like me who wish to install every flatpak needed to play videogames in one go.
=> feat(cli): Add install-gaming-flatpaks ujust command

packages.json
Add Samsung printer and scanner drivers, this should fix #1550 and #1604
I fixed an issue with files in /opt in the negativo17 repository: https://github.com/negativo17/uld/pull/3
Now the package should not break the build anymore.
=> Add samsung unified linux driver

build_files/base/03-install-kernel-akmods.sh
During pre-release when RPM Fusion is getting ready to support a new Fedora release, there are often rough spots. This allows a beta build to succeed for other dev purposes even if RPM Fusion would otherwise be blocking.
=> chore: beta should build even if rpmfusion isn't working

bluefin_flatpaks/flatpaks
Saves us a runtime on the ISO.
=> feat(packaged): switch from fedora media writer to impression

iso_files/configure_iso.sh
This config file is not configured for bootc, but allows us to startup the installer without it crashing.
=> chore(liveiso): add config file

packages.json
This is in homebrew as `stress`
=> fix(packages): remove stress-ng

packages.json
Let's ditch this for F42, it's up to date in homebrew anyway. Do not merge until F42
=> fix(packages): remove topgrade

packages.json
=> fix(dx): remove devpod from the image

just/bluefin-apps.just
Replace ProtonUp-Qt with ProtonPlus is more suitable for Gnome DE(Bazzite use it on GNOME ver) add steamtinkerlaunch for more advanced users and gamers
EDIT: Adding also Protontricks.
I think these two tools are quite essential to have if we already providing mangohud and gamescope  + Swap for libadwaita based ProtonPlus.
=> feat(cli): replace ProtonUp-Qt with ProtonPlus

dx_flatpaks/flatpaks
Noticed on aurora that the "install-system-flatpaks" ujust scripts breaks because the devpod flatpak has a capital D on its name instead a lowercase
=> fix: correct name for devpod flatpak

build_files/base/00-image-info.sh, iso_files/configure_iso.sh
This writes `nvidia-open` instead of `nvidia` for the open kmod images, should work but I havent checked it yet.
Also makes it so the ISOs have the right container name there
=> fix(nvidia-open): correctly identify nvidia-open on image-info.json + fix live ISO nvidia

build_files/base/03-install-kernel-akmods.sh
Also partial revert "feat: install v4l2loopback from terra (#2339)"
This reverts commit 3ff7e659d827648c0a7435f5ed7f711226e17929.
Also this removes the terra installed v4l2loopback in a partial revert of commit fa23c87eaef6677dfb44ac816a0c390923e908dc.
The reason for this revert back to rpmfusion for `v4l2loopback` is that the terra package seems to be trying to build the binary kmod in our bluefin build... if we want terra's v4l2loopback, we should first switch to building the binary kmod in akmods repo if we can make that work.
=> Revert "feat: remove v4l2loopback and rpmfusion for Fedora 42+ (#2330)"

build_files/dx/04-override-install-dx.sh, packages.json
Docker have now updated the stable repos to contain F42 packages, so we can switch to that.
=> chore: install Docker CE from stable repos

.github/workflows/build-image-beta.yml, .github/workflows/build-iso-live.yml
Now that F42 is in the latest image, we don't need beta.  
latest and beta are identical.
Keeps the workflow around for when F43 comes around.
=> chore: remove beta builds

iso_files/configure_iso.sh
Install from the nightly package while there's no release with (working) bootc support
=> chore(liveiso): install Readymade from nightly

build_files/base/09-hwe-additions.sh
Iptsd doesn't appear to be available from sueface-linux right now.
=> fix(hwe): switch to skip-unavailable

iso_files/configure_iso.sh
Fixes: https://github.com/ublue-os/titanoboa/issues/71
And is a partial fix for: https://github.com/ublue-os/titanoboa/issues/70
=> fix(live-iso): nvidia kargs + readymade on autostart

iso_files/configure_iso.sh
Fedora's livesys scripts package overrides the `favorite-apps` dconf key with their own thing, this is most likely why we werent getting readymade on the dock
=> fix: reinstall bluefin-schemas on the live ISO

iso_files/configure_iso.sh
This just removes the liveinst symlink so we dont have two readymades and then removes the NoDisplay from the desktop file
=> fix: make readymade show up on the dock on newer builds

iso_files/configure_iso.sh
Can be merged once we get any release with this commit applied https://github.com/FyraLabs/readymade/commit/d5599cd8cf5303d11c19e511239dc4a02066bf76
Fixes: https://github.com/ublue-os/titanoboa/issues/79
=> chore(live-iso): hide custom partitioning button

.github/workflows/build-iso-live.yml
One hour after readymade-nightly, remove PR builds.
=> chore(iso): build nightly

build_files/dx/01-install-copr-repos-dx.sh, build_files/dx/09-cleanup-dx.sh
Incus in F42 is blocked moving past 6.8.
This change re-enables the ganto copr for incus packages.
=> fix(incus): re-enable ganto copr for incus

iso_files/configure_iso.sh
This just adds the argument we were missing for offline installs on the ISO
Fixes: https://github.com/ublue-os/titanoboa/issues/80
=> fix(live-iso): allow for offline installation

packages.json
need it for keyboard layouts. let's just bury it in the utilities folder
=> fix: readd gnome-tweaks

build_files/base/05-override-install.sh
This straight up just adds the bluefin docs PDF into `/usr/share/doc/bluefin`
=> feat: add bluefin offline documentation to `/usr/share/doc`

build_files/base/17-cleanup.sh, system_files/shared/usr/lib/systemd/system/ublue-fix-hostname.service
We've been getting lots of reports of distroboxes breaking due to not having `/etc/hostname`.
This unit that @p5 wrote just puts your hostname into there if that file doesnt exist yet.
=> fix: add temporary workaround service for missing `/etc/hostname` file

system_files/shared/usr/lib/systemd/system/ublue-fix-hostname.service
The previously solution could overwrite the user's configured hostname. This creates an empty file if it does not exist.
=> fix: /etc/hostname fixup

.github/workflows/build-image-gts.yml, .github/workflows/build-image-stable.yml
This is required because Fedora CoreOS stable moved to a rawhide kernel which isn't available in F41.
=> chore: pin GTS and Stable to kernel 6.13.8

.github/workflows/build-image-gts.yml, .github/workflows/build-image-latest-hwe.yml, .github/workflows/build-image-latest-main.yml, .github/workflows/build-image-stable.yml, image-versions.yml
The intent here is to monitor silverblue-nvidia and then build right after instead of cron timing.
I've left gts and stable as weekly builds because they should just remain that way. LMK if I did this right. 🗡️
=> feat(ci): switch to renovate from cronjobs

just/bluefin-system.just
A recent change introduced a regression, where the whole "ujust dx-group" script is running under pkexec, which means the $USER variable is now expanded "root" and not a current user.
To fix this, use just substitution to inject current user into the script.
=> fix(just): add current user to dx-groups instead of root

.github/workflows/build-iso-live.yml, iso_files/configure_iso.sh
Just adds a little workaround for terra and LTS on the workflows
=> feat(live-iso): add live ISO workflow for LTS too

iso_files/configure_iso.sh
Previous one was faulty cuz it didnt actually read the version
=> fix(live-iso): handling for LTS readymade installation

build_files/base/03-install-kernel-akmods.sh, system_files/shared/usr/lib/bootc/install/20-bluefin.toml
This just adds a default filesystem type for Bluefin (btrfs) (makes it so bootc install to-disk works w/o modifications), and adds nvidia kargs on nvidia builds, shouldnt affect anything retroarctively
Fixes: https://github.com/ublue-os/titanoboa/issues/70
=> chore: add a few upstream bootc configuration files for nvidia and `bootc install`

just/bluefin-system.just
This pull request updates the way `gsettings` is called within the `ptyxis-transparency` just recipe. I spent a significant amount of time over the weekend trying to achieve this, encountering some unexpected challenges.
Initially, I attempted to use `gsettings` and `dconf` (as suggested in [this gist](https://gist.github.com/andypiper/f75c25d91548af03fe586a19f35c9742)) to modify the opacity. However, these methods didn't seem to work as expected.
Ultimately, [this Stack Exchange answer](https://askubuntu.com/a/1007851) provided the necessary solution. I have another installation of `gsettings` (not sure what added it) which was being used instead of the system one.
p.s. Thanks for the hard work put into this project! It's been an amazing experience setting it up and a great way to learn …
=> fix(just): use system gsettings to configure terminal transparency

build_files/dx/01-install-copr-repos-dx.sh, just/bluefin-system.just, system_files/dx/usr/lib/systemd/system/bluefin-dx-groups.service, system_files/dx/usr/libexec/bluefin-dx-groups
This PR removes LXD from the script to add the user to certain "dx" groups. It also removes references to LXD from comments in various files.
=> chore: remove LXD from group scripts and references - Fixes #283

Justfile
Embeds the correct image and flatpaks but uses the older anaconda version on F41 that isn't broken.
Hopefully we can get F42's installer working again.
=> chore: pin iso's to use F41 for installer

.github/workflows/build-iso-lts.yml, Justfile
Only build main.
This is a temporary build process until this moves to bluefin-lts repo.
=> fix(iso-lts): handle fedora version for Centos

.github/workflows/reusable-build-iso-readymade.yml
Makes it so the live ISOs follow the same formatting from the documentation, should be something like:
`readymade-bluefin-(flavor)-(tag)-(arch).iso`
But for specifically GDX its `readymade-bluefin-gdx-(arch).iso`
=> fix: correctly name live ISOs

build_files/base/17-cleanup.sh, system_files/shared/etc/yum.repos.d/charm.repo
gum and glow are in fedora repos
=> chore: remove redundant charm repo

system_files/shared/usr/lib/systemd/system/ublue-fix-hostname.service
bad casing in unit file, fixed.
```
May 14 21:06:39 beast systemd[1]: /usr/lib/systemd/system/ublue-fix-hostname.service:2: Unknown key 'name' in section [Unit], ignoring.
May 14 21:06:39 beast systemd[1]: /usr/lib/systemd/system/ublue-fix-hostname.service:3: Unknown key 'description' in section [Unit], ignoring.
May 14 21:06:39 beast systemd[1]: /usr/lib/systemd/system/ublue-fix-hostname.service:4: Unknown key 'after' in section [Unit], ignoring.
```
=> fix: ublue-fix-hostname unit errors

system_files/dx/usr/libexec/bluefin-dx-groups
`/etc/ublue` doesn't exist, but the dx-groups service is trying to read a file from there, then write one later. This fix creates the directory.
=> fix: create devmode version directory

build_files/base/17-cleanup.sh
=> fix: turn on input remapper service on by default

Justfile
Users are reporting that the F42 ISO is experiencing crashes of the wayland session.
This forces the installer to use F41. This does not affect the target install but will just report that it is F41 in the top right corner.
=> fix(iso): Use F41 for ISO

build_files/base/18-workarounds.sh
This PR fixes a major regression with Atheros firmware, where the current firmware prevents the kernel from loading the module.
https://bugzilla.kernel.org/show_bug.cgi?id=220108
https://bugzilla.redhat.com/show_bug.cgi?id=2365882
https://www.reddit.com/r/archlinux/comments/1kja6f9/ath12k_regression_on_latest_linuxfirmware_upgrade/
=> fix(pin): linux-firmware to 20250410

system_files/dx/usr/share/ublue-os/user-setup.hooks.d/10-vscode.sh
This is replaced upstream, existing users get prompted to upgrade within vscode anyway
=> fix: update docker extension to container extension

build_files/base/18-workarounds.sh
Avoids https://bugzilla.redhat.com/show_bug.cgi?id=2369147
=> fix: pin mutter to .48.1-1 in F42

build_files/base/18-workarounds.sh
mutter 48.3-2 is in F42 now. 
Reverts ublue-os/bluefin#2594
=> revert: "fix: pin mutter to .48.1-1 in F42"

system_files/shared/usr/bin/ublue-rollback-helper
This PR adds fedora versions next to the rebase tag. Those are not hardcoded and use `skopeo` to extract the version.
Then jq is used to extract `org.opencontainers.image.version`, which is usually `gts-41.xx`, `latest-42.xx` or `42.xx` for stable and stable-daily. That's why `sed` is used to match everything before the `-`. `cut` is then used to only retrieve the 41/42 part.
`choose_target=${choose_target%% *}` allows matching everything after the first space and remove it.
Related to #1526
=> feat: Add fedora version to the rebase helper

system_files/shared/usr/share/ublue-os/bazaar/config.yaml
This darkens the background images for the Bluefin banners used in the Bazaar App Store and makes the text more readable and legible. It also improves padding with the text inside the banners.
=> feat(bazaar): darken background images and improve padding

packages.json
=> fix(bazaar): ship in F42 only

packages.json
=> fix: syntax

system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Faster Scratch alternative/fork, also verified on flathub. Big fan of scratch, haven't used it in a while but it was super helpful in learning CS concepts when I was younger.
=> feat: add turbowarp to "education" section in bazaar

build_files/base/18-workarounds.sh
Pulling in https://github.com/ublue-os/bazzite/pull/2859.
=> fix(bazaar): add NVIDIA workaround

.github/workflows/build-image-stable.yml
Next CoreOS seems to move to 6.15.4 kernel which is affected by the btrfs bug. We should pin stable until a fixed kernel version is available (looks like 6.15.6 is still affected)
=> chore: pin stable to kernel 6.14.11

build_files/base/18-workarounds.sh
fix bazaar crashes under VMs and low spec PCs
=> fix(pin): downgrade libdex to 0.9.1

.github/ISSUE_TEMPLATE/feature_request.yml
This must have come from the old main repo or something.
=> chore: remove image dropdown

.github/workflows/reusable-build.yml, Justfile
We are mixing the container storages which leads to the builders running out of space
ported:
https://github.com/ublue-os/aurora/pull/732
https://github.com/ublue-os/aurora/pull/745
in Aurora it seems to work
=> fix(ci): use rootful container storage

.github/workflows/reusable-build-iso-anaconda.yml
so we don't have to upload to CF each time
=> feat: add optional cloudflare upload to Anaconda Live ISO workflow

packages.json
we're going to the use the brew package. it keeps getting out of date, let's cut out the distro
=> fix: remove ramalama from image

.github/workflows/generate-release.yml
This should be set to a normal release. That way gts releases show up as normal. Otherwise downstream automation will have out of date info.
=> chore(ci): set prerelease to false in release workflow

flatpaks/system-flatpaks.list
For some reason this is boxbuddy instead of the current list, fixing.
=> fix: use distroshelf and not boxbuddy

.github/workflows/build-image-gts.yml, .github/workflows/build-image-stable.yml
Unpin the kernels in gts and stable.
Needs https://github.com/ublue-os/akmods/pull/401 to be merged
=> chore: unpin gts and stable kernel

system_files/shared/usr/share/ublue-os/system-setup.hooks.d/10-framework.sh
Two changes:
1. The suspend workaround is specific to Framework 13 Ryzen 7040 but we're also applying it to the recently released Ryzen AI 300 models. These don't need the workaround.
2. The 3.5mm jack workaround is needed for all Framework 13 models. The kernel code applies this workaround automatically for most current Intel/AMD framework models, but it's missing the new Ryzen AI 300. It doesn't seem to hurt to apply this workaround explicitly even when the kernel does it (we've been doing so for the Ryzen 7040 for some time now) so I loosened the condition to apply it to all models.
I've tested this on a Framework 13 Ryzen AI 300. If anyone could test on other Framework 13 models (especially the Ryzen 7040) that would be appreciated!
=> fix: update logic for applying framework laptop 13 fixes

.github/workflows/reusable-build-iso-anaconda.yml
Remove concurrency so we can generate lts, lts-hwe, etc by firing off the action multiple times.
Otherwise they cancel each other out.
=> chore(iso): remove concurrency
