ublue-os/bluefin

etc/dconf/db/local.d/01-ublue

These apparently don't need quotes? fml.

fix: formatting for values

---

.github/workflows/build.yml

Let's goooooooooooooooooooo...

feat: enable F38 builds

---

Containerfile

This PR adds apx, custom built to work with Silverblue

feat: add apx

---

Containerfile

This PR adds `fleek`'s man page.

feat: add fleek man page

---

Containerfile

update location of fleek man page

fix: man location

---

packages.json

So it doesn't collide with yafti

fix: remove gnome-tour

---

packages.json

This commit adds zsh to the default install.

feat: add zsh

---

usr/bin/ublue-nix-install

Create the nix daemon override directory before trying to write a file to it.

fix: create directory before putting file there

---

usr/bin/ublue-nix-install

replace determinate systems installer, which wants to write to read-only places

fix: nix installer - switch back to nixos

---

.github/workflows/build.yml

So that client side tools checking for versions have what they expect

chore(ci): add same version tag as Fedora

---

Containerfile

copy fleek's autogenerated man pages into the right places in the container.

feat: fleek autogenerated man pages

---

.github/workflows/release-please.yml

Yafti solved this already so using Marco's method.

chore(ci): Move ISO generation to release please

---

.github/workflows/release-please.yml

revert: "chore(ci): split upload action into it's own so it can find docker"

---

Containerfile

changes the source of man pages and adds shell completions to the image for fleek

feat: add fleek man and completions

---

etc/yafti.yml

Forgot to put this back! Fixes #156

feat: add blackbox to initial install wizard

---

.github/workflows/release-please.yml

chore(iso): update to combo ISO generator

---

usr/bin/ublue-nix-install

feat: added lines of code that makes a backup of nix before it is used so user can reset nix easily

---

Containerfile

gnome-software prompts to enable these on new installs, let's see if removing them fixes it.

fix: remove extra repo files from final image

---

etc/dconf/db/local.d/01-ublue

fix: set first-run to false

---

packages.json

fix: remove podman-docker from F38

---

.github/workflows/release-please.yml

We're not building the ISOs here anymore

chore(iso): remove isogenerator

---

etc/justfile

We'll put touch and 2in1 goodies in `just touch`

feat: add a just shortcut for better OSK

---

.github/workflows/build.yml

chore(ci): remove extra push step

---

etc/dconf/db/local.d/01-ublue

fix: remove gnome-software settings

---

packages.json

For remoting in for stuff, easier for new users if it's just on the image

feat: add tmux

---

Containerfile.toolbox

Adding a more polished default terminal

feat: add Containerfile.toolbox

---

Containerfile.toolbox

From: https://github.com/toolbx-images/images/blob/main/ubuntu/22.04/Containerfile

fix: update toolbox containerfile

---

Containerfile.toolbox

fix: update Containerfile.toolbox

---

.github/workflows/release-please.yml

Now that this is fixed we can generate bluefin ISOs

chore(ci): add isogenerator

---

toolbox-packages

See https://github.com/Xfennec/progress

feat: add `progress` tool

---

etc/justfile

feat(just): add improved gestures extension

---

etc/justfile

Now that includes are available in the config repo we can start to generalize this and move the common functions into the config repo, this is the first step

feat(just): add includes for ublue justfiles

---

etc/yafti.yml

This is a nice self contained install of syncthing which is nice and easy.

feat(yafti): add syncthing flatpak

---

usr/bin/ublue-nix-install
usr/share/ublue-os/just/custom.just

Update the nix installer to latest version.
Add Just target to install nix + devbox.
Add Just target to install devbox global profile.

feat: update nix tools

---

README.md

Drop the expat thing, we don't need it.

docs: change the description

---

packages.json

To use monitor tools, this might make more sense in the main repo so I'll move it there if this works out.

feat: add ddcccontrol

---

packages.json

Package is tiny, purpose is to allow client management from a remote machine with minimal deps. There's a new version upstream that looks like it would be a perfect fit for us so I want to prototype setting it up.

feat: add cockpit-bridge

---

.github/workflows/build.yml
Containerfile

Making an image that implements this: https://knowledgebase.frame.work/en_us/optimizing-fedora-battery-life-r1baXZh

feat: add a framework specific image

---

framework/etc/tlp.conf

From: https://knowledgebase.frame.work/en_us/optimizing-fedora-battery-life-r1baXZh

feat(framework): ship a default tlp config

---

toolboxes/packages.wolfi

Conflicts with procps, will figure out later.

fix(wolfi): remove uutils

---

etc/yafti.yml

I think this should meet the requirements for https://github.com/ublue-os/bluefin/issues/305.

feat: add Gnome Next Meeting Applet to yafti

---

Containerfile

It's easier to just turn this on so more tools work ootb.

feat(dx): enable podman socket

---

usr/share/ublue-os/just/custom.just

This will refresh and replace all the distroboxes you've defined in /etc/distrobox/distrobox.ini

feat(just): add an assemble shortcut

---

etc/dconf/db/local.d/01-ublue

This should fix the shortcut on first boot

fix: no need to run custom command

---

Containerfile

This was spamming selinux logs

fix(dx): disable pmie service

---

Containerfile

This got dropped, it should be on here.

feat(dx): re-add cockpit

---

.github/workflows/build.yml

Let's run on these for a while, should work out to less than $20 a month.

chore(ci): add buildjet

---

usr/share/ublue-os/just/custom.just

fix: specify user and shell in justfile lchsh commands

---

Containerfile

upstream's not really into podman-compose, since we are working on the socket anyway let's just ship the real thing.

feat(dx): add docker-compose

---

usr/share/ublue-os/just/custom.just

sshd needs to be running for cockpit-ws to work

fix(just): enable sshd for cockpit

---

Containerfile

Adds podmansh for container-confined users

feat: add podmansh package

---

etc/yafti.yml

fix(yafti): Fix ffmpeg-full installation

---

etc/distrobox/distrobox.ini

So people can recreate their distroboxes.

feat(distrobox): leave an additional_packages example

---

dx/etc/dconf/db/local.d/01-ublue-dx

Just leave it stock, fixes #335

fix(dx): remove nerd font

---

framework/etc/dconf/db/local.d/01-ublue-framework

feat(framework): Set text scaling factor

---

Containerfile

add some missing packages to enable vfio and lxd virtualization.

feat: some missing packages for virtualization

---

Containerfile

Need to find a clean way to also include completion for bash/zsh but that could be a userland/`just` follow-up :)

feat: add kns and kctx tools to bluefin

---

.github/workflows/build.yml

chore(ci): I guess we need PR checks

---

etc/distrobox/distrobox.conf

This should ensure that the right image is pulled on initial usage

fix: add back a distrobox.conf

---

Containerfile

fix: disable pmlogger service

---

.github/workflows/build-fedora-toolbox.yml
dx/etc/distrobox/distrobox.ini
toolboxes/Containerfile.fedora
toolboxes/packages.fedora

Inspired by the ubuntu & wolfi image we currently deliver. 
This should provide our users with a fresh and up to date toolbox image for fedora.

feat: add fedora image

---

Containerfile

feat: add bootc COPR

---

packages.json

feat: add solaar

---

packages.json

Coming in F39: https://fedoraproject.org/wiki/Changes/Color_Bash_Prompt

feat: add bash-color-prompt

---

Containerfile

small typo in the repo name. :sweat_smile:

fix: remove bootc repo

---

dx/usr/share/ublue-os/distrobox/pytorch-nvidia.ini

Fix: Update pytorch-nvidia.ini to latest images

---

packages.json

Let's add this for now for laptop battery testing and stuff.

feat: add stress-ng

---

Containerfile
packages.json

since the workaround is already in main https://github.com/ublue-os/main/pull/334

feat: revert cjk fonts workaround

---

usr/share/ublue-os/just/custom.just

I had to log out and back in order for docker to work, I think if we add this here we should be good but I'm not sure.

fix: add user to docker group

---

usr/share/ublue-os/just/60-custom.just

Depends on the following PR landing:
https://github.com/ublue-os/config/pull/118

feat: Switch to new justfile system

---

Containerfile

Please wait for this to merge: https://github.com/ublue-os/main/pull/367

fix: remove bootc since it's in main

---

packages.json

We only need 2 small libraries to get davinci working on the host, so adding it here. cc @KyleGospo

feat: add davinci deps

---

dx/usr/etc/dconf/db/local.d/01-ublue-dx
usr/etc/dconf/db/local.d/01-ublue

A shortcut that matches Windows' <kbd>Control</kbd> + <kbd>Shift</kbd> + <kbd>Escape</kbd>

feat: open Mission Center on CTRL + SHIFT + ESC

---

usr/etc/yafti.yml

fix: update yafti

---

README.md

fix: 404 in readme

---

Containerfile

The nerd-fonts are now available via the ublue-os staging copr.

chore: switch nerd-fonts copr to ublue-os staging

---

Containerfile
packages.json

feat: add tailscale extension

---

Containerfile

This restores kmods removed from Fedora 39

chore(f39): Restore kmods removed from main

---

.github/workflows/build.yml
Containerfile

Installs kmods specific to the kernel/image flavor being used as ASUS and Surface no longer include these

fix(f39): Install kernel specific kmods

---

usr/etc/flatpak/user/install

This should be in the default install

fix: add back celluloid

---

packages.json

feat: swap out tailscale extension

---

Containerfile

feat: turn on ublue-update service

---

just/custom.just

Just a small nice thing when enabling cockpit.
I had to look up how to access it.

Add cockpit link in just output

---

.github/workflows/build.yml

No reason to build the images when updating the readme

chore(ci): ignore markdown files

---

.github/workflows/build.yml

Move build schedule back for official images

chore(ci): Build at 4:40 PM UTC

---

usr/etc/yafti.yml

feat(yafti): add podman desktop

---

usr/lib/systemd/user/ublue-user-setup.service

https://github.com/ublue-os/bluefin/issues/575
Big thanks to Liaralabs for finding the problem.

fix: Correct issues with desktop portal

---

usr/lib/sysctl.d/80-inotify.conf

feat: increase inotify handles

---

just/custom.just

feat(just): enable/disable gnome-vrr

---

just/custom.just

Runs the Homebrew uninstaller.
#576

Add 'brew-remove' just recipe

---

usr/etc/dconf/db/local.d/01-ublue

This is a better default, people can turn it on in tweaks if they want.

feat: turn off login sounds by default

---

just/custom.just

Prepare the just file for the new syntax check action :partying_face:

chore(just): fix indentation for format checker

---

packages.json

Cause monitor wonkiness for some users.  Fixes #663

fix: remove ddccontrol

---

packages.json

Add support for hp printers. Fixes #677

feat: add hplip

---

packages.json

adds missing incus-agent package

fix: add incus-agent

---

packages.json

Was removed from main so re-adding here.

feat(dx): add podman-compose

---

toolboxes/packages.wolfi

Adding in some recommended packages. We'll make a brew one and a vanialla one.

feat(wolfi): add packages needed

---

packages.json

This is small anyway, fixes #729

feat(dx): add make back

---

Containerfile

And add the user to the docker group

feat(dx): turn on docker socket by default

---

packages.json
usr/etc/dconf/db/local.d/01-ublue

This is better integrated with the desktop

feat: switch to tailscale-gnome-qs extension

---

usr/etc/dconf/db/local.d/01-ublue

It's a no-brainer to have this enabled out-of-the-box imo

feat: Enable num-lock by default

---

Containerfile

https://gitlab.freedesktop.org/upower/power-profiles-daemon/-/merge_requests/127

feat: add patched power-profiles-daemon

---

.github/workflows/build.yml
Containerfile

https://github.com/wagoodman/dive
This is useful for inspecting container sizes, etc but needs to be on the image.

feat: add dive command

---

toolboxes/packages.bluefin-cli

This should help people adjust to wolfi

feat(dx): add command-not-found

---

.github/workflows/build-bluefin-toolbox.yml
.github/workflows/build-wolfi-toolbox.yml

This verifies the base container for wolfi against Chainguard's certificate before building the wolfi and bluefin toolboxes

feat(toolbox): Verify wolfi-base before building

---

README.md

Some links in README.md are using http instead of https - this PR fixes this

fix: Update README.md to update the http links to https

---

Containerfile

Requires https://github.com/ublue-os/akmods/pull/115

chore: Remove now unneeded xpad-noone driver

---

Containerfile
packages.json
usr/etc/ublue-update/ublue-update.toml
usr/share/ublue-os/just/10-update.just
usr/share/ublue-os/topgrade.toml

feat: Switch to topgrade powered ublue-update

---

.github/workflows/build.yml

Used for testing new features before they end up in latest

feat(ci): Introduce a testing tag

---

usr/share/ublue-os/motd/design/bluefin.md

Kyle made me do it, I'm sorry Benjamin.

feat: jazz up the motd

---

just/custom.just

Time to slim em down. Thanks for the podmansh spike @jeefy - The Final Shape is nearly complete.

feat(just): remove things we don't use from the justfile

---

usr/etc/profile.d/user-motd.sh

Merge after https://github.com/ublue-os/config/pull/208 is merged and in upstream main/nvidia/asus/surface/etc.

refactor: remove local user-motd.sh mod as it is now provided upstream

---

usr/share/ublue-os/topgrade.toml

chore: match bazzites topgrade.toml

---

usr/share/ublue-os/topgrade.toml

Revert "chore: match bazzites topgrade.toml"

---

just/custom.just

We're moving these outta here, too complicated and deferring to the assembles from config

fix(just): clean up distroboxes

---

usr/libexec/enable-bluefin-cli.sh
usr/libexec/prompt-add-profile.sh
usr/libexec/prompt-create-profile.sh
usr/libexec/prompt-remove-profile.sh
usr/share/ublue-os/bluefin-cli/known-containers

Prevent multiple profiles from being created for same container
Have list of known containers
Set palettes for known containers.
Ability to set default profile and palettes when creating profiles
Handle opacity if already set on default profile

feat: improve prompt integration with quadlets

---

Containerfile
just/custom.just

feat: Get Atuin from bluefin-cli

---

usr/bin/vscode-distrobox

From @89luca89 
`vscode-distrobox name-of-distrobox /path/to/project`

feat: vscode-distrobox script

---

packages.json

I was told this wasn't acceptable in main, so I am proposing it here and in bazzite instead, as I use those variants.

feat: Add rclone to packages so that you can use it to mount cloud storage

---

.github/pull_request_template.md

chore: add a pull_request_template.md

---

.github/workflows/build_iso.yml

Please [read the Contributor's Guide](https://universal-blue.org/CONTRIBUTING/) before submitting a pull request.

fix: action name

---

README.md

Please [read the Contributor's Guide](https://universal-blue.org/CONTRIBUTING/) before submitting a pull request.

docs: add links to dx images

---

.github/workflows/build_iso.yml

Please [read the Contributor's Guide](https://universal-blue.org/CONTRIBUTING/) before submitting a pull request.

chore(ci): fix isogenerator version

---

CHANGELOG.md

Revert "chore(main): release 1.4.1"

---

.github/pull_request_template.md

Please [read the Contributor's Guide](https://universal-blue.org/CONTRIBUTING/) before submitting a pull request.

chore(ci): update pull_request_template.md

---

packages.json

fix: update packages.json

---

.github/workflows/build_iso.yml

fix!: enable asus and surface builds

---

just/custom.just

adds `just brew` to install homebrew manually
adds `just brew-fleek LEVEL` to install fleek packages for brew

feat: just install brew, fleekbrew

---

just/custom.just

fix: remove noninteractive=1 from brew

---

just/custom.just

fix: warning for brew

---

just/custom.just

fix: clarify instructions

---

.github/workflows/build_iso.yml

This includes fixes for SECURE_BOOT_KEY_URL and allowing all languages to be available in the installer.

feat: Update isogenerator to latest version

---

usr/etc/dconf/db/local.d/01-ublue

We'll leave the boxes for ubuntu and fedora alone for now.

fix: change ctrl-alt-enter to host term

---

dx/usr/etc/zsh/zshrc
dx/usr/share/fish/vendor_conf.d/brew.fish
usr/etc/profile.d/brew.sh

fix: Make this check if brew is installed before trying to run it.

---

usr/etc/profile.d/brew.sh

check the directory, not the command for sourcing brew shellenv

fix: check for directory, not command

---

just/custom.just

thanks Hikari for the pointer.

fix: remove quotes around level

---

usr/etc/dconf/db/local.d/01-ublue

feat: change to spring wallpaper

---

Containerfile

feat: Add Explicit sync patches for XWayland on Nvidia builds

---

usr/share/ublue-os/just/10-update.just

chore: Bring in 10-update.just improvements from Bazzite

---

usr/etc/dconf/db/local.d/01-ublue

Correcting a small typo in the local.d file.

fix: Correcting small typo from title-bar-font to titlebar-font.

---

usr/share/ublue-os/topgrade.toml

fix(topgrade): ignore helm, ignore npm errors

---

.github/workflows/build_iso.yml

chore(ci): enable asus and surface nvidia builds

---

usr/share/ublue-os/topgrade.toml

fix(topgrade): npm should be node

---

packages.json

feat: add bcache-tools

---

packages.json

feedback from mastodon, it's like 2.6M.

feat: add epson printer drivers

---

.gitattributes

fix: add gitattributes for proper linguist detection

---

.devcontainer/devcontainer.json
.github/dependabot.yml

feat: initial devcontainer

---

packages.json

For making custom selinux policies for containers

feat: add udica

---

just/bluefin-apps.just

fix: remove brew install, it's in config now

---

usr/share/ublue-os/topgrade.toml

revert: "fix: disable topgrade git extension"

---

.github/FUNDING.yml

feat: create FUNDING.yml

---

.github/workflows/build_iso.yml

Testing to see if latest version will allow this to work

chore(ci): Use rclone action to install latest version

---

.github/workflows/build_iso.yml

Revert "chore(ci): Use rclone action to install latest version"

---

packages.json

feat: add ROCm support to -dx

---

usr/libexec/ublue-flatpak-manager

fix: change this into a welcome message

---

Containerfile
build.sh
packages.json

Restores formatting from before commit ce18074 and changes how power-profiles-daemon is replaced.

chore: fix build issues related to tuned-ppd

---

just/bluefin-tools.just

fix(just): remove yafti

---

Containerfile
just/bluefin-apps.just

These should be brew installed, leaving kind on the image though.

fix: remove binaries from image

---

Containerfile

do vrr and ptyxis in 39
ptyxis only in 40

chore: vrr for 39 only, ptyxis for both

---

packages.json

Wow I can't believe we're only realizing this one now lol.

feat: add caffeine extension

---

.github/workflows/build_iso.yml

Use the complete path to the ISO instead of uploading the entire directory that contains the ISO

fix: use path

---

packages.json

fix: remove vestigial internal cockpit component

---

.github/workflows/build-38-bluefin.yml
.github/workflows/build-39-aurora.yml
.github/workflows/build-39-bluefin.yml
.github/workflows/build-40-aurora.yml
.github/workflows/build-40-bluefin.yml

chore(ci): don't build aurora for bluefin changes and vice-versa

---

just/bluefin-system.just

Adds support for aurora to the devmode toggle

chore(devmode): Add support for aurora

---

build_files/base/install-akmods.sh

fix: temporaliy disable v4l2loopback for 39

---

.github/workflows/reusable-build.yml

fix(ci): fix variable names for gts/latest tagging

---

README.md

docs(aurora): initial aurora description

---

.github/workflows/reusable-build-iso.yml

Aurora_isos_testing

---

.github/workflows/build-aurora-iso.yml
.github/workflows/build-bluefin-iso.yml
.github/workflows/reusable-build-iso.yml
.github/workflows/reusable-build.yml

feat: aurora and bluefin iso build workflows

---

README.md

docs: add coverage and build badges

---

packages.json
system_files/silverblue/usr/etc/dconf/db/local.d/01-ublue

feat: add gnome searchlight

---

system_files/silverblue/usr/etc/dconf/db/local.d/01-ublue

fix: turn on search-light

---

packages.json

chore: move fastfetch to bluefin

feat: add dynamic wallpaper pkg Aurora

---

build_files/base/copr-repos.sh
build_files/base/systemd.sh
packages.json

fix: remove tuned

---

packages.json

fix: don't exclude power profiles and tlp

---

packages.json
system_files/shared/usr/etc/profile.d/askpass.sh

feat: add askpass config

---

system_files/shared/usr/libexec/ublue-system-setup

Use bash arrays. Only run the script if it hasn't been updated.
Only adds luks discard option if there is a luks disk.

fix: update ublue-system-setup

---

system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md

Remove ones that are on the website, add some others.

docs(motd): update motd

---

.github/FUNDING.yml

chore(funding): Add myself to FUNDING

---

.github/FUNDING.yml

chore: funding bketelsen

---

system_files/shared/usr/libexec/distrobox-quadlet-ptyxis.sh

fix: update quadlet popup messages

---

just/bluefin-system.just

feat: add a flatpak install for rebasers

---

system_files/kinoite/usr/share/ublue-os/motd/bluefin.md

feat(motd): recommend ujust choose in the motd.

---

system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md

docs(motd): add ollama snippet

---

build_files/base/cleanup.sh
system_files/shared/usr/share/ublue-os/ublue-os.jsonc

chore: remove fastfetch aliases for F38

---

build_files/base/copr-repos.sh
system_files/shared/usr/libexec/ptyxis-create-profile.sh
system_files/shared/usr/libexec/ublue-flatpak-manager
system_files/shared/usr/libexec/ublue-image-info.sh
system_files/shared/usr/libexec/ublue-motd
system_files/shared/usr/libexec/ublue-privileged-user-setup
system_files/shared/usr/libexec/ublue-system-setup
system_files/shared/usr/libexec/ublue-user-setup
system_files/shared/usr/share/ublue-os/ublue-os.jsonc

chore: cleanup shellcheck warnings

---

system_files/silverblue/usr/share/ublue-os/motd/bluefin.md

feat(motd): suggest ujust --choose in motd

---

README.md

docs: update Bluefin screenshot

---

.github/workflows/build-aurora-iso.yml

fix(ci): Update Aurora ISO to 40

---

README.md

This commits update the screenshot in the readme to one with Fedora 40 and the new theme applied.
This PR updates the screenshot in the readme to one with Fedora 40 and the new theme applied.

chore(readme): Update the Aurora Screenshot in the Readme

---

system_files/kinoite/usr/share/fish/vendor_conf.d/aurora-fastfetch.fish
system_files/silverblue/usr/share/fish/vendor_conf.d/bluefin-fastfetch.fish

This PR updates the alias for fastfetch with the new layout and design in the fish config too, like bash.

chore: update alias for new fastfetch config for fish shell

---

system_files/kinoite/usr/share/icons/default/index.theme
system_files/shared/usr/share/ublue-os/ublue-os.jsonc

chore: fix sddm cursor and fetch color

---

.github/workflows/reusable-build.yml

fix: remove already sunset framework builds

---

system_files/shared/usr/etc/skel/.local/share/flatpak/overrides/com.google.Chrome
system_files/shared/usr/etc/skel/.local/share/flatpak/overrides/com.visualstudio.code

fix: enable common flatpak overrides

---

system_files/shared/usr/etc/profile.d/neofetch.sh
system_files/shared/usr/share/fish/vendor_conf.d/noefetch.fish

chore: restore neofetch alias

---

build_files/base/copr-repos.sh

fix(bluefin): remove mutter patch on 40

---

system_files/silverblue/usr/etc/profile.d/bluefin-fastfetch.sh

fix: actually shuffle dinos

---

build_files/shared/initramfs.sh

fix: initramfs permissions

---

packages.json

feat(aurora): enable kde filesharing

---

packages.json

fix(dx): Restore Devpod to F40

---

build_files/base/copr-repos.sh
build_files/base/fetch-install.sh
build_files/base/fetch-quadlets.sh
build_files/base/install-akmods.sh
build_files/dx/copr-repos-dx.sh

chore(ci): use curl instead of wget to avoid wget2 errors.

---

build_files/base/cleanup.sh
build_files/base/copr-repos.sh
build_files/base/fetch-install.sh
build_files/dx/cleanup-dx.sh
build_files/dx/copr-repos-dx.sh

fix: correct ublue-update and disable rpmfusion/coprs after build time

---

packages.json

feat: add support for old Brother printers

---

build_files/base/copr-repos.sh

Much smoother experience for iGPUs of all kinds -- feature parity with Ubuntu.

feat: Add GNOME Triple Buffering support in F40 Bluefin

---

packages.json

revert: "feat: Add back xwayland video bridge to all images"

---

system_files/shared/usr/libexec/ublue-system-setup

chore: Fix missing then in setup script

---

.github/ISSUE_TEMPLATE/bug-report.yml

chore: add `groups` command to issue template

---

Containerfile

feat(framework): Use older mt7921e firmware

---

.gitignore
Justfile
build_files/shared/image-info.sh
scripts/build-iso-ghcr.sh
scripts/build-iso.sh
scripts/run-iso.sh

feat(dev): make iso just commands work

---

Containerfile

Do not merge until https://github.com/ublue-os/akmods/pull/195 is merged.

chore(ci): kvmfr module in common

---

.github/workflows/reusable-build-iso.yml

chore(ci): let cron work for ISOs

---

system_files/kinoite/usr/share/ublue-os/motd/bluefin.md
system_files/silverblue/usr/share/ublue-os/motd/bluefin.md

feat(brew): Add example to motd

---

Containerfile
build_files/base/brew.sh
build_files/base/fetch-install.sh
system_files/shared/usr/lib/systemd/system/brew-setup.service
system_files/shared/usr/lib/systemd/system/brew-update.service
system_files/shared/usr/lib/systemd/system/brew-upgrade.service

chore: use brew's installer

---

system_files/shared/usr/share/fish/vendor_conf.d/brew.fish

Update brew.fish. Related issue: https://github.com/ublue-os/bluefin/issues/1304
Its my first pull request to the project. Sorry for the inconvenience

fix: brew.fish

---

Containerfile
build_files/base/brew.sh
system_files/shared/usr/lib/systemd/system/brew-setup.service

chore: use compression for brew on disk.

---

system_files/silverblue/usr/etc/dconf/db/local.d/01-ublue

feat: Use ublue icon by default in Logo menu

---

system_files/shared/usr/lib/systemd/system/brew-update.timer
system_files/shared/usr/lib/systemd/system/brew-upgrade.service
system_files/shared/usr/lib/systemd/system/brew-upgrade.timer

Have the two timers have 20 minutes of seperation.

chore: stagger brew timers

---

build_files/base/fetch-quadlets.sh

chore: integrate brew into quadlets

---

system_files/kinoite/usr/share/plasma/look-and-feel/dev.getaurora.aurora.desktop/contents/splash/Splash.qml
system_files/kinoite/usr/share/qt5/qtlogging.ini
system_files/kinoite/usr/share/qt6/qtlogging.ini

fix(aurora): kf.svg log spam and splash gear size

---

system_files/kinoite/usr/share/ublue-os/motd/bluefin.md
system_files/silverblue/usr/share/ublue-os/motd/bluefin.md

fix(motd): shorten motd descriptions

---

packages.json

feat: add lm_sensors

---

README.md

fix: update initial description

---

just/bluefin-system.just

We'll put this in yafti, plus it implies we support these extensions.

fix: remove vestigial extensions command

---

system_files/shared/usr/share/ublue-os/ublue-os.jsonc

feat(motd): add install date

---

system_files/shared/usr/share/ublue-os/ublue-os.jsonc

fix(motd): be less boring than bazzite

---

system_files/shared/usr/share/ublue-os/ublue-os.jsonc

Fixes: https://github.com/fastfetch-cli/fastfetch/issues/987
Also partially https://github.com/ublue-os/bazzite/issues/1190

fix: fix bad fastfetch output in kitty

---

bluefin_flatpaks/flatpaks

Clapper is awesome, let's switch to it, installed systems won't see a change.

feat: switch to Clapper from Celluloid

---

system_files/silverblue/usr/etc/dconf/db/local.d/01-ublue
system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-summer-dynamic.xml

Please don't merge until 31 May.
Welcome back Lords of Summer!

feat: switch to summer wallpaper set

---

system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-autumn-dynamic.xml
system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-spring-dynamic.xml
system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-summer-dynamic.xml
system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-winter-dynamic.xml

Corrects remaining wallpapers with fixes found to be needed for summer wallpaper

fix: Correct timing issues on dynamic wallpapers

---

system_files/silverblue/usr/etc/dconf/db/local.d/01-ublue

fix: revert back to spring wallpaper

---

system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-autumn-dynamic.xml
system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-spring-dynamic.xml
system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-summer-dynamic.xml
system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-winter-dynamic.xml

Testing well in my VM, no longer able to reproduce orange color. Checked 2AM, 6AM, 12PM, 2PM, 6PM, and 9PM.

chore: Simplify rules for dynamic wallpapers

---

system_files/silverblue/usr/etc/dconf/db/local.d/01-ublue

Thanks to @KyleGospo for figuring out this fade bug!

feat: switch to summer wallpaper

---

packages.json

feat: add foo2zjs

---

system_files/shared/usr/etc/profile.d/nix-app-icons.sh
system_files/shared/usr/etc/zsh/zshenv

chore: remove nix references

---

Containerfile
build_files/base/build-base.sh
build_files/base/firmware.sh

chore: cleanup containerfile

---

bluefin_flatpaks/flatpaks

Newly uploaded to flathub, gtk4 continuation of Evince, new maintainers, etc.

feat: switch to GNOME Papers

---

system_files/shared/usr/share/applications/Documentation.desktop
system_files/shared/usr/share/ublue-os/bluefin/docs.svg

Links to https://universal-blue.discourse.group/docs?topic=2291

Added a .desktop shortcut to documentation

---

.github/workflows/reusable-build.yml

Revert "feat: Add kernel signer to sign Fedora kernel with ublue's keys for secure boot"

---

.github/workflows/reusable-build.yml

Reverts ublue-os/bluefin#1405
This is embarrassing lol!

Revert "Revert "feat: Add kernel signer to sign Fedora kernel with ublue's keys for secure boot""

---

packages.json

feat: add krb5-workstation

---

system_files/shared/usr/share/fish/vendor_conf.d/brew.fish

#1363 
Remove the create links.

chore: remove fish brew completions link

---

Justfile

fix(just): installer typo

---

.github/workflows/build-39-aurora.yml
.github/workflows/build-39-bluefin.yml
.github/workflows/build-40-aurora.yml
.github/workflows/build-40-bluefin.yml

https://github.com/ublue-os/main/pull/589
https://github.com/ublue-os/hwe/pull/254/files

fix: adjust build schedule based on adjustments to main and hwe

---

build_files/shared/image-info.sh

feat: Update VARIANT_ID in /etc/os-release

---

.github/renovate.json5
.github/workflows/validate-renovate.yml

Disables auto-rebase and creates a workflow to validate all changes to the configuration before merging

chore(ci): disable Renovate auto-rebase

---

build_files/base/fetch-install.sh
just/bluefin-apps.just
just/bluefin-system.just
system_files/shared/usr/share/ublue-os/bluefin-cli/bling.fish
system_files/shared/usr/share/ublue-os/bluefin-cli/bling.sh

feat: bluefin cli now sources bling

---

.github/workflows/build-bluefin-stable-iso.yml

chore(ci): build stable ISOs

---

build_files/shared/initramfs.sh
system_files/shared/usr/lib/dracut/dracut.conf.d/95-nvidia.conf
system_files/shared/usr/lib/modprobe.d/nvidia.conf
system_files/shared/usr/lib/modprobe.d/nvk.conf

fix: remove conflicting nvidia initramfs files

---

.github/workflows/build-39-aurora.yml
.github/workflows/build-39-bluefin.yml
.github/workflows/build-coreos-aurora.yml
.github/workflows/build-coreos-bluefin.yml
.github/workflows/reusable-build.yml

chore(ci): Switch GTS/Stable to only Scheduled builds. Build ISOs weekly for GTS with schedule

---

system_files/kinoite/usr/share/ublue-os/motd/bluefin.md
system_files/silverblue/usr/share/ublue-os/motd/bluefin.md

Helps with: https://universal-blue.discourse.group/t/how-to-get-rid-of-welcome-message-in-ptyxis/2589/2

fix(motd): clarify banner toggle wording

---

build_files/dx/build-dx.sh
build_files/dx/fonts-dx.sh

Closes #660 
Adds Monaspace fonts onto the DX image.

feat(dx): add monaspace font

---

.github/workflows/build-bluefin-latest-iso.yml

chore(ci): bluefin latest fedora version

---

build_files/base/install-akmods.sh

fix: correct zfs install

---

build_files/dx/cleanup-dx.sh
build_files/dx/copr-repos-dx.sh
packages.json

Adds `umoci` for incus oci container support.
Can be removed when incus removes umoci dependency in the future.

feat: add umoci for incus container support

---

system_files/shared/usr/bin/ublue-rollback-helper

This should make the channel selection clearer.

feat(just): Add descriptions to rebase-helper

---

system_files/silverblue/usr/etc/dconf/db/local.d/02-bluefin-folders

feat: move utilities into the utility folder

---

packages.json

feat: add opendyslexic font

---

.github/workflows/reusable-build-iso.yml

chore(ci): explicitly use v1.2.1 for ISO action

---

packages.json

https://github.com/Netflix/bpftop

feat: add bpftop

---

system_files/shared/usr/share/applications/Documentation.desktop

This is already better than what we have an by the time the new ISOs etc come out it'll be even better.

fix: update project documentation link

---

.github/workflows/reusable-build-iso.yml
README.md
scripts/build-iso-ghcr.sh
scripts/build-iso-installer-main.sh
scripts/build-iso.sh

fix: update secureboot password

---

packages.json

https://github.com/ublue-os/bluefin/issues/1543
Adds the package to fix this issue.

feat: add rocm-smi

---

.github/workflows/reusable-build.yml

chore(ci): fix gts kernel version check

---

system_files/shared/usr/libexec/ublue-user-setup

fix: clear flatpak's font cache

---

system_files/shared/usr/share/ublue-os/homebrew/kubernetes.Brewfile

Added the initial kubernetes.Brewfile

---

system_files/shared/usr/share/wireplumber/wireplumber.conf.d/10-disable-camera.conf

thanks kyle for implementing this in bazzite first

fix: Disable pipewire camera handling temporarily

---

system_files/shared/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile

Great for quick disk space checking on the CLI.

feat(bluefin-cli): add dysk

---

README.md

docs: update public key filename

---

build_files/install-akmods.sh

fix: disable evdi

---

just/bluefin-tools.just

... instead of silently doing nothing. Fixes #1607

make `ujust ollama` show help

---

system_files/silverblue/etc/dconf/db/local.d/01-ublue

feat: switch to autumn wallpapers

---

build_files/install-akmods.sh

Kyle recommends just matching bazzite.

fix: remove xpadneo

---

README.md

This PR removes the broken Aurora badges that were under the title and did not work. Makes it look the same as Bluefin.

chore(readme): remove broken aurora badges from readme

---

just/bluefin-system.just

According to the docs the alias comes first.

fix(just): fix rebase-helper aliases

---

system_files/kinoite/etc/skel/.config/gtk-3.0/gtk.css

will fix this [issue on Chromium based browser ](https://github.com/flathub/org.gtk.Gtk3theme.Breeze/issues/94)

feat: fix weird titlebar on chromium

---

just/bluefin-tools.just

No description was visible in `ujust --choose`.

docs: Added description to invokeai entry

---

packages.json

feat: add setools-console

---

build_files/branding.sh
build_files/image-info.sh

fix: fix os-release naming

---

system_files/shared/usr/share/ublue-os/ublue-os.jsonc

fix: Don't show version, Use only Pretty Name

---

system_files/silverblue/usr/share/fish/vendor_conf.d/bluefin-fastfetch.fish

Resolves part of https://github.com/ublue-os/bluefin/issues/1715.
Tested locally on a virtual machine. Works!
[Screencast from 2024-10-11 00-25-13.webm](https://github.com/user-attachments/assets/fdb32c93-9ffb-401c-a63c-53a9d4fa903a)

feat: add random dinos to fish fastfetch

---

.github/ISSUE_TEMPLATE/bug-report.yml

chore: update bug-report.yml

---

build_files/cleanup.sh

chore: disable autostart behavior for solaar

---

system_files/kinoite/usr/share/applications/documentation.desktop
system_files/shared/usr/share/applications/Documentation.desktop
system_files/silverblue/usr/share/applications/documentation.desktop

Response to https://github.com/ublue-os/bluefin/pull/1789.
They both use the same Universal Blue logo, but maybe that can change in the future.

chore(docs): Separate Bluefin and Aurora documentation 

---

.github/workflows/reusable-build.yml
Containerfile
build_files/install-akmods.sh

fix: don't attempt to pull zfs on beta

---

just/bluefin-system.just

fix(just): change dx-group to a reboot message

---

aurora_flatpaks/flatpaks
bluefin_flatpaks/flatpaks
packages.json

feat: add adw-gtk3-theme

---

system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override

revert: "fix: match bazzite's vrr/fractional scaling options"

---

.github/workflows/reusable-build.yml

chore: fix GTS source fedora version

---

build_files/build-base.sh
build_files/build-fix.sh

chore: fix builds by enabling updates

---

.github/workflows/reusable-build.yml

chore(ci): Don't pull zfs on latest.

---

build_files/install-akmods.sh

fix(framework): turn the framework akmod back on

---

.github/workflows/reusable-build.yml

chore(ci): fix stable-daily image signing

---

.github/workflows/generate-release.yml

chore(ci): fix typos in generate-release workflow

---

.github/workflows/reusable-build.yml

chore(ci): cosign signing for legacy hwe support

---

.github/workflows/reusable-build-iso.yml
Justfile

chore(ci): fix build-iso workflow/justfile

---

build_files/base/09-hwe-additions.sh

Re-add old surface modules-load file.

chore(hwe): 09-hwe-additions.sh

---

.github/workflows/build-iso-latest.yml
.github/workflows/generate-release.yml
.github/workflows/reusable-build-iso.yml
Justfile

chore(ci): fix iso names for cloudflare bucket

---

.github/changelogs.py

fix: changelogs only need 2 tags

---

.github/ISSUE_TEMPLATE/bug-report.yml

chore: update issue template to bootc

---

.github/workflows/build-image-latest.yml
.github/workflows/build-image-stable.yml
.github/workflows/generate-release.yml

fix(ci): correct weekly schedule trigger

---

Justfile

fix: correct iso name for run-iso

---

build_files/base/18-workarounds.sh

Fixes #1943 
Pin this for now.

fix: pin pkcs11-provider to 0.5-3.fc41

---

.github/ISSUE_TEMPLATE/pin.yml

chore: add pin package issue template

---

.github/workflows/clean.yml

chore(ci): add remaining images for cleanup

---

packages.json

feat(packages): Add `ddcutil` 

---

.github/workflows/build-image-beta.yml
.github/workflows/build-image-latest.yml
.github/workflows/build-image-stable.yml
.github/workflows/build-iso-latest.yml
.github/workflows/build-iso-stable.yml

chore: turn off aurora builds

---

README.md

This was a sentence fragment, fixing.

docs: update description

---

.github/FUNDING.yml

I'm on the Aurora team now 
<sub> i still run bluefin on my laptop though 🤫 </sub>

chore: Replace myself with tulizrockz for project sponsorship

---

bluefin_flatpaks/flatpaks

feat(iso): add File Roller by default

---

.github/workflows/build-image-beta.yml
.github/workflows/build-image-gts.yml
.github/workflows/build-image-latest.yml
.github/workflows/build-image-stable.yml
.github/workflows/generate-release.yml

This adjusts bluefin's crons another +5m. This means bazzite, aurora, and bluefin will pack the queue in relative serial order.

chore(feat): adjust cron timers

---

.github/changelogs.py

fix: remove aurora from changelogs

---

.github/workflows/build-iso-latest.yml
.github/workflows/build-iso-stable.yml
.github/workflows/clean.yml
.github/workflows/reusable-build-iso.yml
.github/workflows/reusable-build.yml
boot_menu.yml

chore: remove more aurora mentions

---

system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override

This defers the dock theme to blur my shell

feat: set dash-to-dock to apply built-in theme

---

README.md

ublue-os/bluefin fix: Update README.md with the correct project introduction link

---

build_files/base/01-build-fix.sh

fix: Add skew fixes

---

build_files/base/03-install-kernel-akmods.sh

This may or may not fix broadcom wireless? 
Fixes #1783

fix: remove wl akmod

---

bluefin_flatpaks/flatpaks

This is in gnome tweaks but that thing is on life support. This app is by the warehouse author.

feat: add ignition for startup apps

---

system_files/shared/etc/rpm-ostreed.conf

docs: clarify localayering info

---

.github/workflows/build-image-latest.yml
.github/workflows/build-iso-latest.yml
.github/workflows/reusable-build-iso.yml
.github/workflows/reusable-build.yml
Justfile
build_files/base/03-install-kernel-akmods.sh

feat: add nvidia-open images

---

system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override

feat: switch to january wallpapers

---

README.md

docs: fix italics

---

system_files/shared/usr/bin/sb-key-notify

See: 
https://github.com/ublue-os/aurora/pull/74

fix: add shebang to /usr/bin/sb-key-notify

---

artifacthub-repo.yml

fix: artifacthub id

---

.github/workflows/build-image-gts.yml
.github/workflows/build-image-stable.yml

fix(pin): pin to kernel 6.11.11

---

build_files/base/18-workarounds.sh

Reverts ublue-os/bluefin#2119
Fixes #2124

revert: "fix(pin): sssd to 2.10"

---

build_files/base/09-hwe-additions.sh

Load pinctrl before Surface aggregator

fix(hwe): Fix keyboards on Surface devices

---

Containerfile
build_files/base/01-build-fix.sh
build_files/base/02-install-copr-repos.sh
build_files/base/03-install-kernel-akmods.sh
build_files/base/04-packages.sh
build_files/base/05-override-install.sh
build_files/base/09-hwe-additions.sh
build_files/base/17-cleanup.sh
build_files/base/19-initramfs.sh
build_files/dx/01-install-copr-repos-dx.sh
build_files/dx/02-install-kernel-akmods-dx.sh
build_files/dx/03-packages-dx.sh
build_files/dx/09-cleanup-dx.sh
build_files/shared/build-base.sh
build_files/shared/clean-stage.sh

Reverts ublue-os/bluefin#1954
This confused topgrade so we need to either fix that or remove it.

revert: "chore: un-cliwrap and use dnf5 instead of rpm-ostree"

---

Justfile
build_files/base/09-hwe-additions.sh

fix: just formatting updated on version 1.39

---

build_files/base/05-override-install.sh
build_files/base/17-cleanup.sh
build_files/shared/build-base.sh
packages.json
system_files/shared/usr/share/ublue-os/just/10-update.just

fix: remove ublue-update and rely on units to get auto updates instead

---

Justfile
build_files/base/03-install-kernel-akmods.sh
build_files/dx/02-install-kernel-akmods-dx.sh

Relates: ublue-os/akmods#295
This is expected to fail until the akmods PR is merged.

chore(ci): support combined akmods-kernel-cache in build

---

packages.json

feat(dx): add ramalama

---

just/bluefin-apps.just

add just recipe for opentabletdriver

feat: add opentablet just recipe

---

system_files/shared/etc/geoclue/conf.d/99-beacondb.conf

feat: Fix geolocation (Primarily for timezone detection) now that Mozilla has exited

---

build_files/base/05-override-install.sh

fix: remove old triple buffering patch

---

packages.json

feat: add python3-pygit2

---

.github/workflows/build-image-latest-hwe.yml
.github/workflows/build-image-latest-main.yml

fix(ci): unpin 6.12 kernel in latest

---

.github/workflows/reusable-build.yml

feat: enable sbom generation

---

.github/workflows/reusable-build.yml

I need some time to investigate the failures.
Disable the builds for now since they may block other PRs from being merged.

fix: remove SBOMs temporarily

---

.github/ISSUE_TEMPLATE/config.yml

chorse: update config.yml

---

build_files/base/03-install-kernel-akmods.sh
build_files/shared/build-base.sh

chore: unpin nvidia-install.sh script

---

Justfile

chore: update rechunk version

---

.github/FUNDING.yml

bk's breaking the ingestion on this file by not setting up donations.

fix: update FUNDING.yml

---

build_files/base/05-override-install.sh

chore: Remove patch for GTS bluefin backgrounds

---

.github/workflows/reusable-build.yml

chore(ci): test for buildjet

---

.github/workflows/reusable-build.yml

chore: try buildjet 22.04

---

.github/workflows/reusable-build.yml

chore(fix): finish buildjet/blacksmith test

---

.github/workflows/reusable-build.yml

chore(fix): use ubuntu 24.04

---

.github/CODEOWNERS

Not super sure if @p5 and @m2Giles want to be CODEOWNERS but I personally would like to be one :P

chore: add more CODEOWNERS for this repo

---

bluefin_flatpaks/flatpaks

feat: add refine

---

build_files/base/02-install-copr-repos.sh
build_files/base/03-install-kernel-akmods.sh
build_files/base/05-override-install.sh

feat: install v4l2loopback from terra

---

packages.json

fix(packages): remove simple-scan

---

build_files/dx/04-override-install-dx.sh
packages.json
system_files/dx/etc/yum.repos.d/docker-ce.repo

While they aren't pushed to the stable repos

fix(dx): install docker-ce from test repos in F42

---

dx_flatpaks/flatpaks

Devpod isn't being published yet.

feat(dx): add devtoolbox and devpod

---

.github/workflows/build-iso-live.yml

feat(live-iso): enable GTS builds for live ISOs

---

build_files/shared/build-dx.sh

fix: Enable iptable_nat for docker-in-docker

---

iso_files/configure_iso.sh

Switch back for a day, will switch back tomorrow.
Reverts ublue-os/bluefin#2369

revert: "chore(liveiso): install Readymade from nightly"

---

just/bluefin-system.just

fix(just): adjust flatpak install location

---

iso_files/configure_iso.sh

This straight up just removes the GNOME handling from livesys-scripts.
The goal is to remove all the anaconda branding stuff it does and hopefully remove the dock override it does.

fix(live-iso): dont run any anaconda setup stages

---

iso_files/system-flatpaks.txt

Thunderbird is supposed to be on here anyway, let's add it back. And Pinta is just too good, we want to help expose this app to as many people as possible.

feat(flatpaks): add pinta and thunderbird

---

iso_files/configure_iso.sh

Fixes: https://github.com/ublue-os/titanoboa/issues/78

feat: add mokutil secureboot key enrollment script

---

iso_files/configure_iso.sh

chore(iso): switch back to readymade nightly

---

build_files/dx/01-install-copr-repos-dx.sh
build_files/dx/09-cleanup-dx.sh

revert: "fix(incus): re-enable ganto copr for incus"

---

iso_files/configure_iso.sh

feat(iso): add docs and discourse to live session dock

---

.github/workflows/build-iso-live.yml

Let's see if this works, that way we can test the complete loop daily.

chore(ci): enable stable-daily ISOs

---

system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md

feat(motd): update motd

---

system_files/shared/usr/share/ublue-os/motd/template.md

fix(motd): turn tips back on

---

build_files/base/03-install-kernel-akmods.sh

chore: use main repo for nvidia-install.sh

---

.github/renovate.json5

chore(renovate): configure auto merging for Renovate digest updates

---

iso_files/configure_iso.sh

Useful for installation scenarios.

feat(iso): add gparted

---

iso_files/configure_iso.sh

Can be merged/rerun when https://github.com/ublue-os/packages/pull/403 is on the COPR

fix(live-iso): add branding and fix config file ids

---

iso_files/configure_iso.sh

We want to send people to the bluefin section of the forums not the front page.

fix(iso): fix link to forums

---

build_files/base/03-install-kernel-akmods.sh

chore: fix install of ZFS after update to 2.3.2.

---

.github/workflows/reusable-build-iso.yml

revert: "chore: cleanup reusable build ISO"

---

.github/workflows/reusable-build-iso.yml

chore(ci): update reusable-build-iso.yml

---

.github/workflows/build-iso-gts.yml
.github/workflows/build-iso-latest.yml
.github/workflows/build-iso-stable.yml
.github/workflows/build-isos.yml

revert: "chore: remove old ISO files"

---

.github/workflows/build-isos.yml

chore(ci): don't build latest ISOs

---

bluefin_flatpaks/flatpaks

fix(iso): update ISO flatpak list

---

.github/workflows/build-iso-lts.yml
Justfile

chore(iso): build LTS anaconda ISOs

---

.github/workflows/build-iso-lts.yml
.github/workflows/reusable-build-iso.yml
Justfile

We didn't start building these here.

fix(iso): Build arm64 and gdx LTS ISOs

---

.github/workflows/build-iso-lts.yml
.github/workflows/generate-release.yml
.github/workflows/reusable-build-iso.yml
.github/workflows/reusable-build.yml
Justfile
just/bluefin-system.just

fix(iso): Handle platform differences

---

.github/workflows/build-iso-lts.yml
.github/workflows/reusable-build-iso-anaconda.yml
iso_files/configure_iso_anaconda.sh

feat(iso): Live ISO using anaconda as the installer

---

.github/workflows/reusable-build-iso-anaconda.yml

chore(ci): Change Anaconda Live Cloudflare Bucket

---

.github/workflows/reusable-build-iso-anaconda.yml

fix(iso): anaconda artifact name

---

iso_files/configure_iso_anaconda.sh

feat(iso): remove a ton of fonts

---

.github/workflows/build-image-gts.yml
.github/workflows/build-image-latest-hwe.yml
.github/workflows/build-image-latest-main.yml
.github/workflows/build-image-stable.yml
.github/workflows/reusable-build-iso-anaconda.yml
iso_files/configure_iso_anaconda.sh

fix: improve the live anaconda hook

---

.github/workflows/reusable-build-iso-anaconda.yml

These are much better than what we have, so all good.

fix(iso): push liveCDs to prod

---

packages.json

feat: add bazaar to f42

---

build_files/base/04-packages.sh

fix: pull in fixed xdg-desktop-portal from fedora

---

build_files/base/00-image-info.sh

chore: Change VERSION_CODENAME to Deinonychus in /usr/lib/os-release

---

build_files/base/03-install-kernel-akmods.sh

fix: disable v42l loopback

---

build_files/base/03-install-kernel-akmods.sh

revert: "fix: disable v42l loopback"

---

packages.json

Fixes https://github.com/ublue-os/packages/issues/564

fix: remove nautilus-open-any-terminal

---

system_files/shared/usr/share/ublue-os/bazaar/blocklist.txt
system_files/shared/usr/share/ublue-os/bazaar/config.yaml

add Developers and Bluefin Recommends sections for Bazaar

feat: add more cli text editor to blocklist and add Bluefin Recomends and Developer Tools for Bazaar

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

feat: add more sections and apps

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

feat: add more apps to the appstore

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

feat: add more apps and reorg

---

image-versions.yml

We don't use nvidia so let's just follow this.

fix: kick off build off of silverblue-main

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

fix(bazaar): remove text background

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

feat(bazaar): add more applications

---

bluefin_flatpaks/flatpaks
system_files/shared/usr/share/ublue-os/bazaar/config.yaml

fix(bazaar): update firefox entry

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

fix(bazaar): use proper filenames

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

fix(bazaar): shorter descriptions

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

fix: update config.yaml

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

I'll keep this PR open for a bit while we get recommendations from folks

feat(bazaar): add more apps

---

README.md

docs: add deepwiki button

---

packages.json

Bazaar is already landed, removing this.

feat: remove gnome-software

---

system_files/shared/usr/share/ublue-os/motd/template.md
system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md

fix(motd): update 10-tips.md

---

system_files/shared/usr/share/ublue-os/bazaar/blocklist.txt

fix: blocklist ptyxis flatpak

---

system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md

docs: update tips

---

packages.json

fix(syntax): packages.json

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

This got an update so it's good to recommend for youtube music.

feat(bazaar): add ytmdesktop

---

system_files/shared/usr/share/ublue-os/bazaar/blocklist.txt

This just confuses normal people.

fix(bazaar): blocklist com.google.ChromeDev

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

feat(bazaar): add easyeffects and jamesdsp

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

feat(bazaar): add digger

---

README.md

docs: update deepwiki link

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

add [Constrict](https://flathub.org/apps/io.github.wartybix.Constrict) into utility list

feat(bazaar): add Constrict

---

.github/workflows/reusable-build.yml
Containerfile
Justfile
build_files/base/03-install-kernel-akmods.sh
build_files/base/05-override-install.sh
build_files/dx/04-override-install-dx.sh
build_files/shared/build-base.sh
build_files/shared/build-dx.sh
build_files/shared/utils/ghcurl

Pulling in https://github.com/ublue-os/aurora/pull/709.

fix(build): use GITHUB_TOKEN for curl when needed

---

.github/workflows/reusable-build.yml

chore: try increasing compression on maximize build space

---

README.md

Updating Announcement and discussion links

docs: update links on README

---

packages.json

[`git-svn`](https://git-scm.com/docs/git-svn) is a [separate package on Fedora](https://packages.fedoraproject.org/pkgs/git/git-svn/) (as well as other Linux distros)

feat: add git-svn

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

feat(bazaar): add battle of wesnoth

---

packages.json

feat: add davfs2 to support Taildrive

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

feat(bazaar): add elastic to dev section

---

.github/workflows/reusable-build-iso-anaconda.yml

chore: enable progress on rclone for ISO Cloudflare uploads

---

iso_files/configure_lts_iso_anaconda.sh

This should fix https://github.com/ublue-os/bluefin-lts/issues/653

revert: temporary change due to perms issue with image-info

---

.github/ISSUE_TEMPLATE/config.yml

chore(template): update issue template

---

README.md

docs: new stats for readme

---

just/bluefin-apps.just

fix: add bluefin AI tools ujust

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

Feedback is highly appreciated

feat(bazaar): give each picture a unique gradient

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

feat(bazaar): add io.github.swordpuffin.rewaita to config.yaml

---

.github/changelogs.py

track gnome-shell for the gnome version

chore: update Gnome package reference in changelogs.py

---

build_files/base/18-workarounds.sh

fix: remove a bunch of old workarounds

---

.github/workflows/build-image-latest-hwe.yml

Update workflow triggers for latest images

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

feat: replace Sudoku entry with new package

---

.github/copilot-instructions.md

Update maintainer guidelines in copilot instructions

---

.github/workflows/clean.yml

Add 'bluefin-gdx' to cleanup packages list

---

just/bluefin-apps.just

Fixes https://github.com/ublue-os/bluefin/issues/3212

fix: remove ujust recipes referencing removed Brewfiles

---

flatpaks/system-flatpaks-dx.list

feat(dx): add new clapgrep and concessio

---

packages.json

Very useful soon for many developers near you :)

chore(dx): Add git-subtree
